### ISSUE TITLE
Controller/Route Issue

### ISSUE THREAD

**Issue by jackttcoms** [sonicsleuth/mvc-framework-php#11]
Hello,
I might be being thick but I have created a simple user verify controller method that used to work fine but currently its not working unless I use custom routes which I did not have to use before at all and instead it loads the homepage or home/index controller instead of running the actual code and I can't see why. The system works like so: domain.com/user/verify/email@email.com/4858394968849868394/ which then if correct updates the db but its just really weird as to why its not working! My only suspicion is the $email='' and $code='' because if I do not do the verify/param1/param2 and just verify then it does the check and redirects but after that it just won't work and just very odd so its clearly something to do with the parameters on the url but i'm unsure why? It works fine when I do a custom route but surely it should still work fine without them? Thanks again!

Controller Method:
```
    public function verify($email='', $code='')
    {
        if($email != '' && $code != '') {
            if( $this->user->checkVerifyCode($email, $code) ) {
                $verify = $this->user->verify($email, $code);
                flash('message','User Verified!','alert alert-success mb-0');
               redirect('user/login');
            } else {
                flash('message','User Verification Failed!','alert alert-danger mb-0 fixed-top');
                redirect('user/login');                
            }    
        } else{
            redirect('user/login');
        }
    }
```

Model:
```
    public function checkVerifyCode($email, $code)
    {
        $bind = [
            ':verify_code' => $code, 
            ':email' => $email
        ];
        $results = $this->db->select('msi_users','status = 0 AND email = :email AND verify_code = :verify_code', $bind);
        return $results;
    }
    public function verify($email, $code)
	{
        $bind = [
            ':email' => $email,
            ':verify_code' => $code
        ];
        $update = [
            'status' => '1'
        ];
        $this->db->update('msi_users', $update, 'email = :email AND verify_code = :verify_code', $bind);
        return true;
	}
```

Thanks

**Comment by jackttcoms** [comment]
It's also the same for the profile page which has never used a custom route before but now requires one in order to work! 

I used to simply go to domain.com/user/profile/admin but now it just shows the homepage instead! It's really odd!
```
    public function profile($user_id = '')
    {
        if($user_id == '') { redirect(''); }
        $getSettings = $this->setting->getAll();
        $getCategories = $this->setting->getCategories();
        $getUserData = $this->user->getUserByUsername($user_id);
        $getUserProducts = $this->user->getUserProducts($getUserData[0]['id']);
        $getUserBadges = $this->user->getUserBadges();
        $data = [
            'getSettings' => $getSettings,
            'getCategories' => $getCategories,
            'getUser' => $getUserData,
            'getUserProducts' => $getUserProducts,
            'getUserbadges' => $getUserBadges
        ];
        if($getUserData == false) { redirect('error'); }
        $this->view('user/profile', $data);     
    }
```

**Comment by sonicsleuth** [comment]
FIRST:
When you say "that used to work fine but currently it's not working" can you think of what changes you made to your application before the failure and undo them?  Perhaps that change is the problem.

NEXT:
Let's see what the URL Parser is finding from your URL by dumping its routing values.

Find the following line from within `/app/core/App.php`
`$this->url = $this->parseUrl($config, $route);`

then add below that line to dump and hault the application:
`print_r($this->url); die();`

If nothing appears wrong, continue on...

NEXT:
Let's see what the Params Collector has found in your URL by dumping its routing values.

Find the following line from within `/app/core/App.php`
```
// Rebase Parameters or set empty array.
$this->params = $this->url ? array_values($this->url) : [];
```

then add below that line to dump and hault the application:
`print_r($this->params); die();`

If nothing appears wrong, then there is some new code added that is impacting the routing.  Try digging deeper (see FIRST).

**Comment by jackttcoms** [comment]
Here are the results, very odd in the sense that it used to work fine and just incase I did something, I installed a clean version of the framework!

Verify:
Result is: `Array( [0] => [1] => home [2] => user [3] => verify [4] => email [5] => @email.com [6] => OMIDC0fJd5aHhZSa2zLJEuXPn )` so it appears it does not like the email@ bit! Should this happen?

Profile:
`Array( [0] => [1] => home [2] => user [3] => profile [4] => admin [5] => ) ` - I don't think the ending => should be there!


Thanks and in another quick question, is this too long?

```
    public function index()
    {
        $getSettings = $this->setting->getAll();
        $getCategories = $this->setting->getCategories();
        $getTotalUsers = $this->setting->getTotalUsers();
        $getTotalSalesOrder = $this->setting->getTotalSalesOrder();
		if(isset($_SESSION['uid'])) : $getUserData = $this->user->getUserByUserId($_SESSION['uid']); else : $getUserData = NULL; endif;
        $getSlides = $this->slide->getFeaturedSlides();
        $getFreeItems = $this->item->getFreeItems();
        $getFeaturedItems = $this->item->getFeaturedItems();
        $getNewItems = $this->item->getNewItems();
        
        $data = [
            'getSettings' => $getSettings,
            'getCategories' => $getCategories,
            'getTotalUsers' => $getTotalUsers,
            'getTotalSalesOrder' => $getTotalSalesOrder,
			'getUsers' => $getUserData,
			'userBalance' => $getUserData[0]['main_balance'] + $getUserData[0]['dep_balance'],
            'getSlides' => $getSlides,
            'getFreeItems' => $getFreeItems,
            'getFeaturedItems' => $getFeaturedItems,
            'getNewItems' => $getNewItems,
			'title' => $getSettings[0]['homepage_title'],
			'description' => $getSettings[0]['homepage_desc']
        ];
        $this->view('index', $data);
    }
```
Thanks

**Comment by sonicsleuth** [comment]
I just made an update to the master MVC branch after noticing something in the main URL parser.  Make the following change and let me know if it fixes your @email bug.

Update: `/app/core/App.php` - line 151

From:
`$this->url_string = $this->remapUrl(filter_var(rtrim($_SERVER['PATH_INFO'], '/', FILTER_SANITIZE_URL)), $route);`

To:
`$this->url_string = $this->remapUrl(filter_var(rtrim($_SERVER['PATH_INFO'], '/'), FILTER_SANITIZE_URL), $route);`

The correction above fixes the placement of a paren that appeared after FILTER_SANITIZE_URL.  The similar CASE statements in the SWITCH are OK. Just this one was wonka!

**Comment by jackttcoms** [comment]
Unfortunately that did not :(

Array( [0] => [1] => home [2] => user [3] => verify [4] => email [5] => @email.com [6] => OMIDC0fJd5aHhZSa2zLJEuXPn ) 

What i'm currently doing is rewriting my code to see if I made a silly mistake somewhere but its odd how it worked before and then after I cleaned up my code with tabs it broke!

**Comment by jackttcoms** [comment]
Just out of curiosity, the urls for the user controller which is a separate controller has 'home' in it? Could that be the reason or is this just because its the default controller?

All my user methods are in user controller, all home methods in home controller etc so shouldn't the URLs be like `Array( [0] => [1] => user [2] => verify [3] => email [4] => @email.com [5] => OMIDC0fJd5aHhZSa2zLJEuXPn )`

Thanks

**Comment by jackttcoms** [comment]
My testing for this theory is when I go to domain.com/user/profile/ and leave out the username which usually would result in error but I have the print_r debug bit on and it echos this `Array( [0] => user [1] => profile ) ` but then as soon as I add the username value on the end, it changes to this... `Array( [0] => [1] => home [2] => user [3] => profile [4] => admin [5] => ) `

Thanks

**Comment by jackttcoms** [comment]
I have done more testing and it does like 'words' in the url! For example the custom pages:

<?php if (!defined('BASE_PATH')) exit('No direct script access allowed');

```
class Page extends Controller
{
    public $page;
    
    public function __construct()
    {
        $this->load_helper(['view','session','url','date','custom']);
        $this->setting = $this->model('Settings');
	//	$this->user = $this->model('Users');
        $this->page = $this->model('Pages');
    }
    
    public function index()
    {
        redirect('error');
        die();
    }

    public function p($id)
    {
        $getSettings = $this->setting->getAll();
        $getCategories = $this->setting->getCategories();
        $getPageByName = $this->page->getPageByName($id);
        $data = [
            'getSettings' => $getSettings,
            'getCategories' => $getCategories,
            'getPage' => $getPageByName,
            'title' => 'test'
        ];
        //if($getPageByName == false) { redirect('error'); die(); }
        $this->view('page', $data);     
    }
    
}
```

If I enter domain.com/page/p/terms the array returns like this: Array( [0] => [1] => admin [2] => my-admin [3] => page [4] => p [5] => slug [6] => ); but if I do domain.com/page/p/1 then the array is like this: Array( [0] => page [1] => p [2] => 1 ) and it does not show the homepage meaning it works!

Really odd but let me know what u think! Thanks

**Comment by jackttcoms** [comment]
The @email works now woooo!!! Thanks very much! I would never of spotted that  as I do not edit any of the code in the core :)

Thanks again!

**Comment by sonicsleuth** [comment]
Great to hear it works now. And, good to see your debug approach is thoughtful.

That was a bug in the core parser.  I'm actually amazed it did not show up earlier. That's one downside of PHP... it's very forgiving... until it's not. ;-)

Cheers!

**Comment by jackttcoms** [comment]
Thanks.

Yes exactly, I personally feel PHP need to try and develop/incorporate some better error debugging features that pick up the little errors as they are the ones that usually cause the whole thing not to work and I believe this would help rejuvenate its usage again as unfortunately PHP is losing popularity, even though personally it is one of my favourite languages to code in for side projects and freelancing etc.

Also can I ask you a question regarding the code below... Compared to applications you have made, Is it too long for what I need it to do? -  What the code is doing below is getting all the settings, categories, statistics (total users, total sales), user model if logged in, slides, free items, featured items, new items, adding up the user balance, title and description.
```
    public function index()
    {
        $getSettings = $this->setting->getAll();
        $getCategories = $this->setting->getCategories();
        $getTotalUsers = $this->setting->getTotalUsers();
        $getTotalSalesOrder = $this->setting->getTotalSalesOrder();
		if(isset($_SESSION['uid'])) : $getUserData = $this->user->getUserByUserId($_SESSION['uid']); else : $getUserData = NULL; endif;
        $getSlides = $this->slide->getFeaturedSlides();
        $getFreeItems = $this->item->getFreeItems();
        $getFeaturedItems = $this->item->getFeaturedItems();
        $getNewItems = $this->item->getNewItems();
        
        $data = [
            'getSettings' => $getSettings,
            'getCategories' => $getCategories,
            'getTotalUsers' => $getTotalUsers,
            'getTotalSalesOrder' => $getTotalSalesOrder,
			'getUsers' => $getUserData,
			'userBalance' => $getUserData[0]['main_balance'] + $getUserData[0]['dep_balance'],
            'getSlides' => $getSlides,
            'getFreeItems' => $getFreeItems,
            'getFeaturedItems' => $getFeaturedItems,
            'getNewItems' => $getNewItems,
			'title' => $getSettings[0]['homepage_title'],
			'description' => $getSettings[0]['homepage_desc']
        ];
        $this->view('index', $data);
    }
```

Thanks again for your help!

**Comment by sonicsleuth** [comment]
Your sample is GOOD.  The MVC conventions help keep your code readable. Looking at it myself I can understand what you were attempting to do. Nice!

**Comment by jackttcoms** [comment]
Ok thanks just checking I was not doing anything unconventional that would slow my experimental project down :)

Thanks!

**Comment by jackttcoms** [comment]
BUG: Quick question regarding the view system. I am creating a sticky footer using bootstrap by using flex but it only works if the script is in development mode? As soon as I move it to 'production' the flex stops working? Do you know why this is? Thanks

This is css:
```
html{
  min-height: 100vh;
}
.flex-grow{
  flex: 1;
}
```

This is the view code:
```
<!doctype html>
<html>
<head>
	<!-- Head -->
	<?php extend_view(['common/head'], $data) ?>
	<!-- CSS -->
    <?php load_style(['bootstrap.min','main','custom','slick.min']); ?>
</head>
<body class="d-flex flex-column">
	<!-- Global Messages -->
	<?php echo flash('message'); ?>
	<!-- Header -->
	<?php extend_view(['common/header'], $data) ?>

    <!-- Page Content -->
    <section class="flex-grow">
        
    </section>
    <!-- End Page Content -->

	<!-- Footer -->
	<?php extend_view(['common/footer'], $data); ?>
	<!-- JS -->
	<?php load_script(['jquery-3.2.1.min','bootstrap.bundle.min','main','custom','fontawesome-all.min','slick.min']); ?>
</body>
</html>
```

Also another thing that would probably get on peoples nerves is when the script is in development mode and the view helper causes lots of the warnings which can easily be turned off but i feel it would agitate some developers so is there any way to reduce them?

![image](https://user-images.githubusercontent.com/26184209/43360876-6ddea7e0-92b8-11e8-98e6-8e9a57dc6333.png)

**Comment by sonicsleuth** [comment]
You can customize the level of error reporting you would like by modifying the Environment Error Reporting output control in the `/app/index.php` file. Just update the "developmnet" case with the PHP level of reporting you prefer vs "E_ALL".

```
if (defined('ENVIRONMENT'))
{
    switch (ENVIRONMENT)
    {
        case 'development':
            error_reporting(E_ALL);
            break;

        case 'testing':
        case 'production':
            error_reporting(0);
            break;

        default:
            exit('The application environment is not set correctly.');
    }
}
```

About using Flex - I'm not sure why it would stop working for you. Did you add any special conditions in the Environment controls above?  Try checking your Browser Console log for errors thrown from Flex.

**Comment by jackttcoms** [comment]
Ok thanks and regarding the flex, I re-downloaded an untouched version of your MVC and it did the same! Really odd! I'm using Bootstrap 4.1.2

**Comment by jackttcoms** [comment]
As an update the error system...

```
if (defined('ENVIRONMENT'))
{
    switch (ENVIRONMENT)
    {
        case 'development':
            error_reporting(E_ALL);
            break;
			
	case 'testing':
	    error_reporting(E_ALL & ~E_NOTICE);
            break;

        case 'production':
            error_reporting(0);
            break;

        default:
            exit('The application environment is not set correctly.');
    }
}
```
or...

```
if (defined('ENVIRONMENT'))
{
    switch (ENVIRONMENT)
    {
	case 'development':
	    error_reporting(E_ALL & ~E_NOTICE);
            break;

        case 'mvc': //Mode for when updating/adding to MVC internal (if you can think of better name)
            error_reporting(E_ALL);
            break;

        case 'production':
            error_reporting(0);
            break;

        default:
            exit('The application environment is not set correctly.');
    }
}
```

**Comment by sonicsleuth** [comment]
That is odd.  I just testing switching from dev to prod in two other local sites using the MVC and they work fine in either mode.  My only guess would be that the "ENVIRONMENT" variable is somehow used by the Flex script, meaning a namespace collision.  Try changing "ENVIRONMENT" to "ENV" where applied in the index.php file and see if that fixes it.

**Comment by jackttcoms** [comment]
Oh how odd! Its good that it works for you but strange! I have just quickly done a quick demo so please see attached
[app.zip](https://github.com/sonicsleuth/mvc-framework-php/files/2238872/app.zip)

.. And yes i tried the ENV thing but that did nothing!

**Comment by jackttcoms** [comment]
Its the latest version, all i have done is quickly change certain bits to allow it to work with subdirectories and added the bootstrap files!

**Comment by sonicsleuth** [comment]
The app.zip you attached appeared only to be an untouched original MVC copy.   

If the bug is specific to the Flex scripts, you need to dig into that script and find the conflict.  It's odd there is a bug when toggling the ENVIRONMENT if there are no other global changes you are applying in that CASE. 

A long-shot... check the order of your script that you are loading using the `load_script(['prism', 'main']);` call.  Perhaps the stack is in conflict somehow. (ie: You need to load jQuery before using it for example)

**Comment by jackttcoms** [comment]
No it is touched :) - I just downloaded it myself and the demo bit is all there!

I have added all the bootstrap files and the home controller index shows the bug whereas if you go to development the flex works!

![image](https://user-images.githubusercontent.com/26184209/43367877-eace89da-934b-11e8-95ec-4c2fb4c8bb00.png)
![image](https://user-images.githubusercontent.com/26184209/43367878-fa4159f6-934b-11e8-8369-3ad35cf55494.png)

**Comment by jackttcoms** [comment]
Hmmm, yes it is really odd! I have just tried some of the older versions of your MVC and the issue also occurs there! I also thought it could be hosting debugging so I have tried it on multiple hosts + localhost so still no luck. I just can't see what the issue is! I have tried to isolate it and see if the error messages have some style attached to them but no! It's really odd! I also tried it on an old MVC that I used to use but realised it did not meet my needs so I found yours which is similar build wise and it worked fine on that one but here is a file anyway incase you want to take a look!
[mvcold.zip](https://github.com/sonicsleuth/mvc-framework-php/files/2243199/mvcold.zip)


The script i have been testing most recently is the one above and it has been edited very quickly to work on a subdomain and has a simple template of the flex with the bootstrap library as shown above! Really odd but could it be the view engine even tho that literally just takes all the code etc. Very confusing and very odd! ---And the other zip file with the small error is in above messages!

Thanks again!

**Comment by sonicsleuth** [comment]
I'm going to look deeper into this issue tonight or tomorrow.  Its oddity has captured my curiosity.

**Comment by jackttcoms** [comment]
Ok and yes it is indeed very odd! Please let me know your findings, I would be very intrigued as to why its interfering with the flex.

Thanks

**Comment by sonicsleuth** [comment]
**Good News:** 

After all your head-banging there is a good lesson to learn here - don't let your expectations cloud what you are really looking at.

I fixed the bug under "development mode" that was tossing up the "undefined offset 0" warning at the top of the page.  **The MVC Repo has been updated.**  The Controller needed a fix to handle when no $data was passed to the View.

When the error was appearing on the page it broke the HTML which forced the footer to the bottom of the page... this was NOT a successful implementation of Flex but just a coincident (an illusion of success).

**Seeing past the illustion of success...**

Basically, you had issues implementing Flex...

I first updated your main.css adding a height property to HTML which is needed as a parent reference when adding min-height to the body tag. A body can only be as tall as HTML, so not setting a height on HTML the body was never going to be as tall as the viewport, like so:

```
html{
    height: 100%;
}

body{
    background-color: rgb(244, 244, 244);
    min-height: 100%;
}
```

Then added the missing "align-content-end" CSS property to the footer tag, like so:

`<footer class="bg-dark text-white mt-4 align-content-end">`

I also removed the extra set of BODY tags you have wrapping the JS Script loader.

```
<body>
<?php load_script(['jquery-3.2.1.min','bootstrap.bundle.min','main']); ?>
</body>
```

I also had to remove `/blank` from the FULL_ROOT config to make the app even work.

`define('FULL_ROOT', 'http://localhost/blank');`

In the end, the sticky Flex footer is working fine in both dev/prod modes after my updates.

Carry these updates into your project and you should be fine.  Enjoy!

**Comment by jackttcoms** [comment]
Thankyou very much! Can I apologise for being stupid! I just love how I have indeed been banging my head for 2 days and you just come and fix it in no time at all! One question regarding the extra set of body tags. Did I do that or was that the MVC because if that was me that is even more embarrassing and about the root thing, I did that only so that it would work on a sub directory for testing purposes and also changed the htaccess etc. but thanks again for also getting rid of the evil notice warning! 

Thank you again very much! You have made my day 😁

--------------------------------------------------------------------------

Quick question: Regarding my counters for some reason they do not show 0 when it is 0, instead its all 1. I'm clearly doing something stupid but I cannot see what I'm doing incorrect. I have done a var_dump/print_r but it simply produces int(1) and 1 so I'm being thick but I cannot see what is wrong! Thanks

This is my model code:
```
    public function getTotalSalesOrder()
    {
        $results = $this->db->select('msi_sales','status = 1');
        $totalRows = count($results);
        return $totalRows;
    }
```
This is my controller code:
```
$getTotalSalesOrder = $this->setting->getTotalSalesOrder();
$data = ['
     'getTotalSalesOrder' => $getTotalSalesOrder
']
```
Then in the view i simply echo this: `<?php echo $data['getTotalSalesOrder']; ?>`

Thanks

**Comment by sonicsleuth** [comment]
The additional BODY tags wrapping the JS Loader are not part of the MVC output. Looks like developer error there ;-)

**Comment by jackttcoms** [comment]
How embarrassing on my part! Thanks again!

**Comment by jackttcoms** [comment]
Oh and actually would you be able to send the fixed files you did etc. Thanks

**Comment by sonicsleuth** [comment]
[jack-mvc.zip](https://github.com/sonicsleuth/mvc-framework-php/files/2250000/jack-mvc.zip)
Attached is your example code with applied updates.

**Comment by jackttcoms** [comment]
Back from holiday and just saw your update regarding sessions and its really good! Very helpful! Such a good MVC :) 
--------------------------------------------------------------------

I have one small issue tho regarding a counter! Basically with your MVC and the update model method it will not work if I was to do views + 1 if I was to write it out fully which is fine because that is the lazy way of doing it so instead i'm doing it as shown below...
![image](https://user-images.githubusercontent.com/26184209/44264373-44af7900-a21a-11e8-9da1-5517f3bde084.png)

Then I do a function that counts all the rows in the table but for some reason even if there is 0 rows or 0 items that meet the criteria it always says 1. How do you suggest I fix this? Thanks

My current code:
```
    public function getTotalUsers()
    {
        $results = $this->db->select('msi_users','status = 1');
        $totalRows = count($results);
        return $totalRows;
    }
```

Thanks for building this excellent MVC 🥇
