### ISSUE TITLE
CSRF Protection (Utilities)

### ISSUE THREAD

**Issue by jackttcoms** [sonicsleuth/mvc-framework-php#13]
Hi, quick question regarding classes that always need to be active. I would like to add a CSRF static class that I have built so that when you go on any page it checks if there is a token session and if not generates one but my question is where would i place this class so that it is constant? (Like your session model that keeps updating)!

I'm thinking of placing it in the core folder where i can then put lots of utilities (CSRF, Tokens (for user sessions), Validation, Cookie etc.) but i'm asking basically how best you would you suggest i integrate this with your MVC wihout slowing it down and doing it cleanly?

Functionality = On every page load, refresh etc it checks if there is a csrf token and if not it creates one! But basically im trying to go for 'constant' so how would you suggest i do that as i do not want to individually load each and every function for a class helper in the controller!

Thanks, hope it makes sense.

**Comment by sonicsleuth** [comment]
What you are trying to accomplish is called "middleware" whereby all activity of some type will be processed by something in the middle.  The MCV framework does not support this out-of-the-box, but it can be shoehorned into the Core VIEW functionality.

First, create a CSRF Model with any methods to accomplish your needs.  Then we will add it "inline" to the core `view()` method. This will allow it to be run everytime a view is called.  Note: Controller methods that do not return a View, like an API endpoint, will not invoke your CSRF functions.

**Open `/core/Controller.php` and look for the view method.** My example below includes the changes needed. It's easy to do.

```
protected function view($view, $data = [])
    {
        if(file_exists(VIEWS_PATH . $view . '.php'))
        {
            // Set each index of data to its named variable.
            if( count($data) > 0 ) {
                foreach($data as $key => $value) {
                    $$key = $value;
                }
            }

            // Add middleware here, like so:
            $crfs = $this->model('Crfs');
            $crfs->check_token();

            require_once VIEWS_PATH . $view . '.php';
        } else {
            return false;
        }
    }
```

Rinse and repeat for any other Middleware you need to run before a view loads.

**Comment by jackttcoms** [comment]
Thankyou very very much! Also is `$crfs = $this->mode('Crfs');` that actual code? The mode part? Thanks or was it supposed to be `$this->model`

**Comment by sonicsleuth** [comment]
Typo s/b $this->model().  You are using a Model here just like you would inside of a Controller.  The only difference, placing it here will allow you to "centrally" call functions on every View loading.

**Comment by jackttcoms** [comment]
Thankyou again very much!

**Comment by jackttcoms** [comment]
Custom Routing Question:

I'm building a FAQ and am doing it in the Home Controller and have a function called faq with an `$id = '' `but what i'm trying to do is when the `$id != ''` then load a different view which all works great when you browse to the /home/faq/[id]. Can i just double check i can't do two routes as the browser sees the word 'faq' in the url and then only loads that and then when you add the one on the end it just ignores it so would you suggest i just make a separate controller which would be easier but i'm just testing all the limitations for your MVC and just wondering if this is one of them for custom routing!

```
$route['faq'] = 'home/faq';
$route['faq/:num'] = 'home/faq/$1';
```

I have done a separate function in the home controller as well but then when i try to do the custom routing as the array is in order of importance the first faq is looked at first etc so basically is this a limitation?

Thanks

-----------------------------------------------------------

Feature Request:

For a login system where i'm adding an attempts feature or anti-flood control I need to be able to +1 in the query so would it be possible to create an updateExtended or something.

// Changes to 0
```
    public function updateTest() 
    {
        $update = [
			'status' => + 1
        ];
        $this->db->update('faq', $update, 'id = 1');
        return true;
    }
```
// Does not change, just loads error messages regarding arrays as expected
```

    public function updateTest() // Needs Rewrite
    {
        $this->db->update('faq', 'status + 1', 'id = 1');
        return true;
    }
```

**Comment by sonicsleuth** [comment]
**RE: Custom Routing**

Not a limitation of routing. You just have the stacked in reverse.  The more "specific" URL patterns must appear before the least specific URLs. Do the following and it will work as you require.  This is a common mistake devs make with many other MVC too. ;-)

```
$route['faq/:num'] = 'home/faq/$1';
$route['faq'] = 'home/faq';
```

**IMPORTANT:** Routes will run in the order they are defined. Higher routes will always take precedence over lower ones. Route rules are not filters! _Setting a rule of e.g. ‘foo/bar/(:num)’ will not prevent controller Foo and method bar to be called with a non-numeric value if that is a valid route._

**Comment by sonicsleuth** [comment]
**RE: Update +1**

Because you don't need to BIND any data you can just use the run() method directly like so.  This is also more effecient than passing thru two methods if there were an "UpdateExtended".

```
public function updateTest() 
    {
        $this->db->run ('UPDATE faq SET status = status + 1 WHERE id = 1');
        return true;
    }
```

**Comment by jackttcoms** [comment]
Oh! Thanks very much! A stupid mistake where I did not read your commenting correctly at the top!

Ah! Thanks for that, for some reason i'm just really protective of your MVC and don't wanna fiddle with any of the internal workings because it is the first one that is like a mini-codeigniter just simpler and without the utilties and fits my needs perfectly simple experimental projects! 

Thanks again as always! Really appreciate your help and advice.

**Note: Ignore the most recent message regarding updating with a bind, being thick!**
```

	public function updateTest($id)
	{
		$bind = [':id' => $id];
        $this->db->run('UPDATE faq SET status = status + 1 WHERE id = :id', $bind);
        return true;
	}
```

**Comment by jackttcoms** [comment]
@sonicsleuth  what if i do want to use bind data for an update query and still do `status = status + 1` thanks

**Comment by sonicsleuth** [comment]
Yup, you can also use BINDing with the run() Model method.  It's best to do so to protect against SQL injections.

**Comment by jackttcoms** [comment]
**Regarding Middleware:**

Ok so I have converted this stackoverflow article into a class (https://stackoverflow.com/questions/6287903/how-to-properly-add-csrf-token-using-php) but I'm a little stuck in trying to make it accessible at all times from anywhere almost like utilties in codeigniter. The class works great if I load it in normally and then in the view simply do this which generates the input hidden.

```
	   <form action="" method="POST">
            <?php echo $this->csrf->CSRFInput(); ?>
            <input type="email" name="test" value=""/>
            <input type="submit" value="Submit Test"/>
        </form>
```
What i'm trying to do is make it accessible everywhere without having to reload it, basically being able to call it from anywhere because this is a core security component (almost like codeingiter utilities that can be called from anywhere) for any web application nowadays (if you think that is efficient to load it in always?) Thanks (If not, it is not the end of the world, I will simply just load it in on every controller.)

Here is my CSRF class // (improvements welcome)
```
OLD VERSION - _removed_ (posted improved version further down)
```

Thanks, if not I could always use something like this where i generate the token in the middleware and then write the hidden inputs myself and just refer to the session?
https://github.com/foxbunny/CSRF4PHP


Thanks again as always and let me know improvements if you got any for my csrf class :)

**Comment by sonicsleuth** [comment]
What you are trying to do is referred to as an "anti-pattern", an engineering design pattern that will create future technical debt (issues).  Adding code everywhere even when not required will become inefficient if your app ever scales-up.  The Controller of the MVC pattern has a purpose - "to control the requirements for the output".

It might seem faster/easier to apply some function across the board, but down the road, you need good documentation and/or knowledge about this "invisible" action that may not be referenced in the Controller. (ie: difficult for other developers to understand, or yourself 2 years from today).

I find it cleaner when adding each "requirement" into the Controller as needed.  That said, you can instantiate a common script by adding it to the `__construct() `of a Controller making it available to the whole class vs into each Controller Method.  At least this way, you need only add CRSF to the Controllers that truly need those services.

BTW - your CRSF Model looks good. ;-)

**Comment by jackttcoms** [comment]
Ok thanks very much for the advice! You know best! Efficiency is what I'm after :) Thankyou as always! 

**Feel free to makes changes (better commenting) and add it to your MVC as a come-in-box feature like with your session class!**

Here is latest version (changed labels on a few, added slightly better commenting):
```
<?php if (!defined('BASE_PATH')) exit('No direct script access allowed');

class Csrf extends Model 
{
	public $token; // Holds the CSRF token
	private const TokenExpiry = 250; // Seconds until CSRF token expires

	public function __construct() 
	{
		// Instantiate new Database object
		$this->db = new Model();
	}
	
	public function CSRFInput()
	{
		// This generates the CSRF session and hidden input (does it all)
		$this->CSRFTokenGeneration();
		$this->CSRFCheckGenerate();
		$_SESSION['csrf_expire_check'] = time();
		echo '<input type="hidden" name="csrf_token" value="'.$this->token.'">';
	}

	protected function CSRFTokenGeneration()
	{
		// This generates the CSRF token session
		if(!isset($_SESSION['csrf_token'])) :
			$_SESSION['csrf_token'] = bin2hex(random_bytes(32));
		endif;
	}
	
	protected function CSRFCheckGenerate() 
	{
		// This checks if token exists and then generates the CSRF token string (HASH)
		if(isset($_SESSION['csrf_token'])) :
			$this->token = hash_hmac('sha256', __FILE__, $_SESSION['csrf_token']);
		else:
			die('CSRF token invalid! Refresh the page!');
		endif;
	}

	public function CSRFCheck()
	{
		// This checks if code is valid with session, not expired, blocks requests when attack and forgotten function above (Form Stage, $_POST)
		if(isset($_REQUEST['csrf_token'])) :
			$this->CSRFCheckGenerate();
			if(hash_equals($this->token, $_REQUEST['csrf_token'])) :
				if((time() - $_SESSION['csrf_expire_check'] < self::TokenExpiry)) :
					unset($_SESSION['csrf_token']);
					echo 'PASS';
					return;
				endif;
				die('CSRF Token Expired!');
				return;			
			endif;
			die('Your request has been rejected! CSRF coward!');
			return;
		endif;
		die('Hey buddy using Sonicsleuth MVC, you forgot to call this functon in your form: CSRFInput()');	
	}
    
}
```

Thanks as always!

**Comment by jackttcoms** [comment]
Can you see what is wrong with this update query? Thanks very much!
```
	public function updateCounter($username)
	{
		$date = date("Y-m-d H:i:s");
		$bind = [
			':username' => $username, 
			':date' => $date
		];
        $this->db->run('UPDATE users_attempts SET date = :date AND counter = counter + 1 WHERE username = :username', $bind);
        return true;
	}
```

**Comment by sonicsleuth** [comment]
Looks like your SQL statement is wrong. Replace the AND with a "," like so:

UPDATE users_attempts SET date = :date, counter = counter + 1 WHERE
username = :username

**Comment by jackttcoms** [comment]
Yeah thanks! As soon as I sent the message I realised what I did wrong!

Also regarding sessions, I'm currently planning on adding more security around them such as a user agent checker, last activity(session timout) (even tho it can be manipulated, just that bit extra) but as your session class is what starts the session I was wondering if I can do that in the session class unless you think its already secure enough. But your session class would be perfect to do this as its constant so I won't need to add my own middleware. I have done helper functions to add that extra bit of security for sessions such as timeouts and user agent and if return false then force logout and leave message saying "Session may of been compromised! Please login again!" but I feel it would be better to place it in the session class as its on every controller but I don't know, let me know what you think! Just trying to tie everything together with throttling, login attempts and then session security.

Also if I try to regenerate session id on user login it creates a blank in the database! Is it wrong to regenerate the id? I'm trying to prevent fixation!

I found a few classes online (with some depreciated functions but good features):
https://github.com/tedivm/phpsessionmanager
https://eddmann.com/posts/securing-sessions-in-php/
https://github.com/CVM/Session-Security/blob/master/session_security.php

Thanks as always!

**Comment by jackttcoms** [comment]
With this recaptcha class would you suggest I place it in the models folder for easy accessibility? Thanks

https://github.com/JoelLisenby/recaptcha

**Comment by sonicsleuth** [comment]
Hi Jack,  I would consider this a HELPER addition not a MODEL.  Models are
for "data" in the form of text, images, audio, etc.  Whereas this recaptcha
will enhance "help" some other process.

*Richard Soares*

**Comment by jackttcoms** [comment]
Ok thanks and regarding your file structure on the documentation out of curiosity why have you put / in front of all the files in the config folder? Thanks as always

```
root
    /app
        /config
            /config.php - app configuration /////////////////
            /database.php - settings to connect to your database /////////////////
            /routes.php - custom URL routing patterns ////////////////////
        /controllers
            Docs.php - the controller serving up this documentation
        /core
            App.php - all the magic
            Controller.php - Base controller
            Model.php - Base model
        /helpers
            view.php
        /models
            Users.php - a sample data model
            Sessions.php - database managed PHP Sessions
        /views
            /common
                footer.php - footer of this page
                header.php - header of this page
            /docs
                index.php - this page
        init.php
    /public
        /css - your styles
        /js - your scripts
        index.php - the front-loader and environment configurations
        .htaccess - URL routing to the front-loader
```

And as you were saying to put the recaptcha in a helper because it helps enhance some other process would you do the same for the CSRF then seeing as its just helping to secure a form? Thanks

**Comment by sonicsleuth** [comment]
Check the update. Looks better now.

**Comment by jackttcoms** [comment]
Thankyou and do you have any other extras planned for your MVC like the session model you added recently.

**Comment by sonicsleuth** [comment]
No new addition in the short-term, however, I just posted a Node.js and Python repo showing how to scrape web pages and perform login penetration testing.  Check'em out.

**Comment by jackttcoms** [comment]
Oh ok thanks and probably easisest question you will answer all day but I have a paypal class that has two classes in one file. Is it possible to make this work with your MVC or do I need to separate them?

```
<?php
class PayPalPayment
{
}
class PayPalExecution
{
}
```

In order to do this...
```
    public function __construct()
    {
        $this->load_helper(['view','start','date','email','pagination','recaptcha']);
	$this->user = $this->model('Auth');
	$this->session = $this->model('Session');
	$this->start = $this->model('Start');
	$this->csrf = $this->model('Csrf');
    }
```

Thanks

**Comment by sonicsleuth** [comment]
Difficult to say without knowing how those classes are structured.  Loading it as a Helper may be the better way to go in this case.

**Comment by jackttcoms** [comment]
Yes i think you are right, a helper is probably better and then I can just the the `$payment = new XXXXX `myself Thanks... Also thanks for you MVC being laid out so perfectly! I have 'code OCD' (don't actually) but your code is very well structured great comments and everything is inline so thankyou very much!

As i'm using autoload, where do I place that in your script so it is always loaded? Thanks
`require_once __DIR__ . '/vendor/autoload.php';`

```
<?php
use PayPal\Api\Payer;
use PayPal\Api\Details;
use PayPal\Api\Amount;
use PayPal\Api\Transaction;
use PayPal\Api\Payment;
use PayPal\Api\RedirectUrls;
use PayPal\Api\Item;
use PayPal\Api\ItemList;
use PayPal\Api\PaymentExecution;
use PayPal\Exception\PayPalConnectionException;

class PayPalPayment
{
    public function __construct($paypalApi)
    {
        $this->api = $paypalApi;

        $this->payer = new Payer();
        $this->details = new Details();
        $this->amount = new Amount();
        $this->itemList = new ItemList();
        $this->transaction = new Transaction();
        $this->payment = new Payment();
        $this->redirectUrls = new RedirectUrls();

        $this->transactionDescription = 'Default Transaction Description';
        $this->totalPrice = 0;
    }

    public function setPaymentMethod($method)
    {
        $this->payer->setPaymentMethod($method);
    }
    .................................
}

class PayPalExecution
{
    public function __construct($paypalApi)
    {
        $this->api = $paypalApi;

        $this->execution = new PaymentExecution();
    }

    public function getPayment($paymentId)
    {
        try {
            $this->payment = Payment::get($paymentId, $this->api);
        } catch (PayPalConnectionException $e) {
            return json_encode(array(
                'status' => 'error',
                'message' => $e->getMessage(),
                'data' => $e->getData()
            ));
        }

        return json_encode(array(
            'status' => 'success'
        ));
    }
    ........................
}
```

**Comment by jackttcoms** [comment]
Is it possible to prevent direct access to a certain controller function so that its only accessable when called inside the controller login? Thanks in advance

```
    public function createUserSession($user = '')
    {
        if(!$user == '')
		{
			$_SESSION['uid'] = $user[0]['id'];
			$_SESSION['upin'] = $user[0]['pin'];
			$_SESSION['uemail'] = $user[0]['email'];
			$_SESSION['uname'] = $user[0]['username'];
			$_SESSION['user_agent'] = $_SERVER['HTTP_USER_AGENT'];
			$_SESSION['last_login'] = time();
			flash('message', LANG['login-success'], 'alert alert-success mb-0', 'data-auto-dismiss="10000"');
			redirect('');
		} else {
			redirect('user/login');
		}
    }
```

**Comment by sonicsleuth** [comment]
It is possible to make **Private Class** methods NOT callable.  You will need to change the following section of code in the `/app/core/App.php` file as shown.

Currently, there is an assumption that all methods are Public and callable.  However, calling a Private (or Public Strict) method will result in a PHP error.  

You are going to change the `method_exists()` to `is_callable()` in the following IF statement and in doing so if a method is PRIVATE (or Public Strict) it shall return FALSE and not change the default value of `$this->method` which as a result will call the `index()` method of the Class (so consider that in your logic).

That said, I just updated the MVC repository on Github with this update too.

**CURRENTLY**
```
if(method_exists($this->controller, $this->url[$this->method_index]))
            {
                $this->method = $this->url[$this->method_index];
                unset($this->url[$this->method_index]);
            }
```

**UPDATED**
```
if(is_callable( array($this->controller, $this->url[$this->method_index]) ))
            {
                $this->method = $this->url[$this->method_index];
                unset($this->url[$this->method_index]);
            }
```

**Comment by jackttcoms** [comment]
👍  thanks! This will make it even more powerful and secure.

Also with your style of coding (how many spaces etc.) just wondering which one you use most often from the list below. One with spaces and ones without. Currently I do the top one but which one do you feel is neater and also what is your rule for putting the { on a new line? Sorry if sound confusing, just wondering what your 'rulebook' is when it comes to writing code. Thanks

```
e.g.
if($this->xxx = '5') {
    echo 'contnt';
} else {
    echo 'no';
}

if( $this->xxx = '5' ) {
    echo 'contnt';
} else {
    echo 'no';
}

if( $this->xxx = '5' )
{
    echo 'contnt';
} else {
    echo 'no';
}
```

**Comment by sonicsleuth** [comment]
The top is typical, unless there are deeply nested (parens) then I'll add spacing for clarity.

**Comment by jackttcoms** [comment]
**UPDATE: Don't worry, figured it all out! Just needed to look for another 20 mins Sorry

http://localhost/starter/home/redirect?approved=true&paymentId=PAY-2RW825168A187404ALO4TPZY&token=EC-3HJ082196J960442F&PayerID=J3LNCPLQ7CX3A

Works like a charm 👍** 

--------------------------------------------------------------------------------------

Ok great :)

Can I ask you a question regarding vendor/autoload. What core file would you suggest I place this line of code?

`require __DIR__.'/../../vendor/autoload.php';`

so i can always access the vendor folder and call the paypal rest api class i need?
Thanks

**Comment by sonicsleuth** [comment]
You can add the **/vendor/autoloader** into the` /index.php` file after the last lines of code shown below.  This index file is the MVC's autoloader and is called for every URL.

```
// Build front-loader
require_once '../app/config/config.php';
require_once '../app/config/database.php';
require_once '../app/config/routes.php';
require_once '../app/init.php';
$app = new App($config, $route);

// Add your code here
```

**Comment by jackttcoms** [comment]
Thankyou! Quick question regarding routes, I have the main 'Home' controller with news in and then set a custom route to make it domain.com/news instead of domain.com/home/news but then in the admin controller I also have a news function and for some reason they just do not work unless I change one of the names comppletely. Is it because they both have 'news' in the name?

Thanks

**Comment by sonicsleuth** [comment]
Sometimes possible "name" conflicts may happen, however, most of the time is the stacked order in the file. Stack them most to least complex.  

For example, do this:
/news/article/id
/news/article
/news


Don't do:
/news
/news/article
/news/article/id

**Comment by jackttcoms** [comment]
Yes I have tried that with this but still  not working very odd.

Its a category url -> without url routing it looks like this domain.com/marketplace/categories/X and it works great but then when I add the custom route `$route['categories/:num'] = 'marketplace/categories/$1';` it just shows the homepage. Note I have put it right at the top of the route file still with no luck. Apart from that everything else works. It's the same with all 3 of the first routes **what was your code to do the debugging again?** Thanks

Here is my route file:
```
<?php

$route['default'] = 'home';

$route['categories/:num'] = 'marketplace/categories/$1';
$route['tag/:any'] = 'marketplace/tag/$1';
$route['download/:num'] = 'marketplace/download/$1';
$route['error'] = 'home/error';
$route['contact'] = 'home/contact';
$route['info/:any'] = 'home/page/$1';
$route['news/:num'] = 'home/news/$1';
$route['news'] = 'home/news';

$route['admin/users/edit/:num'] = 'admin/edituser/$1';
$route['admin/users/view/:num'] = 'admin/userhistory/$1';
$route['admin/users/restore-user/:num'] = 'admin/restoreuser/$1';
$route['admin/users/new'] = 'admin/newuser';
$route['admin/users/banned'] = 'admin/bannedusers';
$route['admin/pages/edit/:num'] = 'admin/editpage/$1';
$route['admin/pages/insight/:num'] = 'admin/pageinsights/$1';
$route['admin/pages/new'] = 'admin/newpage';
$route['admin/nav/new'] = 'admin/newlink';
$route['admin/nav/edit/:num'] = 'admin/editlink/$1';
$route['admin/nav/delete/:num'] = 'admin/deletelink/$1';
$route['admin/information/edit/:num'] = 'admin/editnews/$1';
$route['admin/information/delete/:num'] = 'admin/deletenews/$1';
$route['admin/information/new'] = 'admin/newnews';
$route['admin/information'] = 'admin/adminnews';
$route['admin/settings/email'] = 'admin/emailtemplates';

$route['admin/marketplace/slides/delete/:num'] = 'marketplace/deleteslide/$1';
$route['admin/marketplace/slides/edit/:num'] = 'marketplace/editslide/$1';
$route['admin/marketplace/slides/new'] = 'marketplace/newslide';
$route['admin/marketplace/slides'] = 'marketplace/slides';
$route['admin/marketplace/items/categories/delete/:num'] = 'marketplace/deletecategory/$1';
$route['admin/marketplace/items/delete/:num'] = 'marketplace/deleteitem/$1';
$route['admin/marketplace/items/edit/:num'] = 'marketplace/edititem/$1';
$route['admin/marketplace/items/pending-items'] = 'marketplace/pendingitems';
$route['admin/marketplace/items/moderation-items'] = 'marketplace/moderationitems';
$route['admin/marketplace/items/categories/edit/:num'] = 'marketplace/editcategory/$1';
$route['admin/marketplace/items/categories/new'] = 'marketplace/newcategory';
$route['admin/marketplace/items/categories'] = 'marketplace/itemcategories';
$route['admin/marketplace/items/new'] = 'marketplace/newitem';
$route['admin/marketplace/items'] = 'marketplace/items';
$route['admin/marketplace/transactions'] = 'marketplace/alltransactions';
$route['admin/marketplace/withdrawals'] = 'marketplace/allwithdrawals';
$route['admin/marketplace/refund-requests'] = 'marketplace/allrefundrequests';
$route['admin/marketplace/credit-packages'] = 'marketplace/allcreditpackages';
$route['free'] = 'marketplace/free';
$route['sale'] = 'marketplace/sale';
```

Update: It also happens for even simpler URLs:  `$route['search'] = 'marketplace/search';` (does not work) 

I have tried to isolate the issue by turning off all other functions but no luck.

**Comment by sonicsleuth** [comment]
Let's do a few tests to help debug this issue:

**Let's test a basic RegEx Route by displaying an ID passed into it.**

Comment out all of your existing routes from `/app/config/routes.php`

Then add just these two routes:
```
$route['default'] = 'home';
$route['mytest/:num'] = 'docs/mytest/$1';
```
Then add this method to the bottom of the Docs Controller `/app/Controllers/Docs.php`
```
public function mytest($id)
    {
        echo "This works fine " . $id;
    }
```
The above test worked just fine for me.  If this works for you to then I'd say the core MVC router is working fine but there is a route ordering bug in your code someplace.

**Let's have a look at what your routes are returning.**

Remove the above test Routes and Method then uncomment your original Routes.

We are going to dump the Route being returned when the Router processes your custom routes.

Open `/app/core/App.php` and modify the default switchcase found in the `parseURL()` method like so by adding a `die()` statement:

```
default:
     if(isset($_GET['url']))
    {
          $this->url_string = $this->remapUrl(filter_var(rtrim($_GET['url'], '/'), FILTER_SANITIZE_URL), $route);

         die($this->url_string); // <-- ADD THIS LINE OF CODE HERE.

         return $url = explode('/', $this->url_string);
    } else {
         return array();
    }
         break;

```

Now access any of your custom URL's and see if they dump the expected Route.  Do this for each custom route to isolate the issue.

If all your custom routes appear fine, then there may be a looping issue in the routing, meaning the order of routes is rewriting itself someplace.  

If so, try changing the above  `die($this->url_string)` to a  `echo($this->url_string)` and run the tests again. This should print the paths atop your page and maybe you can identify the looping.

One last item to verify... Check which URL parsing method is being used:

Open `/app/config/config/php` and verify the following line is set as shown:

`$config['uri_protocol'] = 'DEFAULT';`

If your routes are still not working, the only other approach for debugging them is to add each one, test, add the next, until you see *when* the issue happens - then refactor the code.

Glad to help.

**Comment by jackttcoms** [comment]
Thankyou very much! Worked wonderfully. Do not know what was interfering but rewriting the controller worked like magic. I did all of this `echo "This works fine " . $id;` and it works great.

Also, what do you use/recomend when you need to get the location/country to check of show a certain piece of data? Thanks as always!

**Comment by sonicsleuth** [comment]
I will assume you are asking about Geolocation based on IP address...

I have used MaxMind [https://www.iplocation.net/](https://www.maxmind.com/en/home) but it is a paid service and requires the install of several large DB tables of data.

I have also used a few of these free services listed on this site here: https://www.iplocation.net/
