### ISSUE TITLE
Bug regarding PDO constructor

### ISSUE THREAD

**Issue by jackttcoms** [sonicsleuth/mvc-framework-php#2]
Hi, I get an error with connecting to the database! It says 

`Warning: PDO::prepare(): SQLSTATE[00000]: No error: PDO constructor was not called in /customers/a/d/5/domain.com/httpd.www/mvc/app/core/Model.php on line 63 Fatal error: Call to a member function execute() on null in /customers/a/d/5/domain.com/httpd.www/mvc/app/core/Model.php on line 64`

Do you know why this is?

I have created a DB and going to the URL domain.com/users/profile/1 which then gives the error.

Here is the controller code:
```
<?php if (!defined('BASE_PATH')) exit('No direct script access allowed');

class Users extends Controller
{
    public function __construct()
    {
        $this->load_helper(['view']);
    }

    public function index()
    {
        $this->view('blog/index');
    }
    
    // Show our User Profile report
    public function profile($user_id)
    {
        // Load the User Model so that we can query the database
        $user = $this->model('User');
        // Get this user
        $bind = [':id' => $user_id];
        $data = $user->select('jh_users','id = :id', $bind);
        // Load the View passing to it the Users information as $data.
        $this->view('users/profile', $data);
    }

    public function phpinfo()
    {
        echo phpinfo();
    }

}
```

Here is the model code:
```
<?php if (!defined('BASE_PATH')) exit('No direct script access allowed');

class User extends Model
{
    public $fname;
    public $lname;
    private $db;

    public function __construct()
    {
       $this->db = new Model();
    }

    public function getName()
    {
        return $this->fname . ' ' . $this->lname;
    }
    
    
    public function getUsers()
    {
        /* get all users */
        $results = $this->db->select("jh_users");
    }

    public function getMaleUsers()
    {
        /* get a specific user */
        $results = $this->db->select("jh_users", "Gender = 'male'");
    }

    public function addUser($fname, $lname, $age, $gender)
    {
        /* add a new user */
        $data = [
                "fname"  => $fname,
                "lname"  => $lname,
                "age"    => $age,
                "gender" => $gender
                ];
        $this->db->insert("jh_users", $data);
    }

}
```

What am i doing wrong or is it database error?
Once all these minor errors are gone i will be on my way and create a awesome application!
Thanks in advance!

**Comment by sonicsleuth** [comment]
Have you set up your DB connection settings in the DB Config file here?  /app/config/database.php

Also, is your database allowing connections from your web server, meaning allow */* for user www-data?

**Comment by jackttcoms** [comment]
this is the database code and it connects successfully!
```
    public function __construct() 
    {
        $options = array(
            PDO::ATTR_PERSISTENT => true,
            PDO::ATTR_ERRMODE    => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_OBJ,
            PDO::ATTR_CASE => PDO::CASE_LOWER
        );

        try {
            parent::__construct(DB_DRIVER . ':host=' . DB_HOSTNAME . ';dbname=' . DB_DATABASE . '', DB_USERNAME, DB_PASSWORD, $options);
            echo 'connects';
        } catch (PDOException $e) {
            $this->error = $e->getMessage();
            error_log('DB Model Connection Error: ' . $this->error, 0);
            echo 'DB Connection Error: ' . $this->error;
        }
    }
```

When i go to the page it echos the 'connects' so the connection is fine and db connection settings are correct! Also all other scripts on my server work fine so im unsure what is wrong! All i know is that the problem is to do with this bit of code

```
    public function run($sql, $bind = "", $entity_decode = true)
    {
        $this->sql   = trim($sql);
        $this->bind  = $this->cleanup($bind);
        $this->error = "";

        try {
            $pdostmt = $this->prepare($this->sql);
    ---        if ($pdostmt->execute($this->bind) !== false) {
                if (preg_match("/^(" . implode("|", array("select", "describe", "pragma")) . ") /i", $this->sql)) {
                    $results = $pdostmt->fetchAll(PDO::FETCH_ASSOC);
                    if($entity_decode) {
                        array_walk_recursive($results, function (&$item) {
                            $item = htmlspecialchars_decode($item);
                        });
                    }
                    return $results;
                } elseif (preg_match("/^(" . implode("|", array("delete", "update")) . ") /i", $this->sql)) {
                    return $pdostmt->rowCount(); // return records affected.
                } elseif (preg_match("/^(" . implode("|", array("insert")) . ") /i", $this->sql)) {
                    return $this->lastInsertId(); // return new record id.
                }
            }
        } catch (PDOException $e) {
            $this->error = $e->getMessage();
            $this->debug();
            return false;
        }
    }
```

and the line with three ---

Very odd but i think it does not like the $pdostmt

Thanks and have u built a simple application using this framework yet?


And i also get this error! Its very confusing - `Fatal error: Cannot redeclare class User in /customers/a/d/5/domain.com/httpd.www/app/models/User.php on line 35 ` What could cause this error?

**Comment by sonicsleuth** [comment]
It's hard to diagnose without access to the code.  Try dumping the $pdostmt and $this->bind to see where an error is being thrown and is it received the "binding" data.

There is no sharable "example" application using this framework I can share but there are live production sites running fine.

**Comment by jackttcoms** [comment]
I'm going to do a clean install and then try again

also do u have any example live production sites i could see?

Thanks again

**Comment by jackttcoms** [comment]
After a clean install and creation of views/user/profile.php + controllers/User.php + models/User.php here is the error i get : Fatal error: `Cannot redeclare class User in /customers/a/d/5/domain.com/httpd.www/app/models/User.php on line 43 `

Line 43 is simply the end of the class '}'

Thanks again

**Comment by sonicsleuth** [comment]
The most likely issue for the "Cannot redeclare class User" error is that you have names both the Controller and Model class "User".  Simply name the Model class Users (plural) and keep the Controller class User (singular).

As for a sample production site, have a look at www.corereadiness.com - I'm not sure how that will help you in any way, especially as this site is using all custom routing patterns vs the /controller/method/ default pattern b/c the site is so large.

**Comment by jackttcoms** [comment]
Thanks, that fixed that bit but now i just get this error!

`Warning: PDO::prepare(): SQLSTATE[00000]: No error: PDO constructor was not called in /customers/a/d/5/domain.com/httpd.www/app/core/Model.php on line 63 Fatal error: Call to a member function execute() on null in /customers/a/d/5/domain.com/httpd.www/app/core/Model.php on line 64 `

I have tried doing the var_dump but i feel like i'm doing it in the wrong location!
This is my code with the var_dump in it!
```
    public function run($sql, $bind = "", $entity_decode = true)
    {
        $this->sql   = trim($sql);
        $this->bind  = $this->cleanup($bind);
        $this->error = "";
        var_dump($pdostmt);
        var_dump($this->bind);

        try {
            $pdostmt = $this->prepare($this->sql);
            if (var_dump($pdostmt->execute($this->bind) !== false)) {
                if (preg_match("/^(" . implode("|", array("select", "describe", "pragma")) . ") /i", $this->sql)) {
                    $results = $pdostmt->fetchAll(PDO::FETCH_ASSOC);
                    if($entity_decode) {
                        array_walk_recursive($results, function (&$item) {
                            $item = htmlspecialchars_decode($item);
                        });
                    }
                    return $results;
                } elseif (preg_match("/^(" . implode("|", array("delete", "update")) . ") /i", $this->sql)) {
                    return $pdostmt->rowCount(); // return records affected.
                } elseif (preg_match("/^(" . implode("|", array("insert")) . ") /i", $this->sql)) {
                    return $this->lastInsertId(); // return new record id.
                }
            }
        } catch (PDOException $e) {
            $this->error = $e->getMessage();
            $this->debug();
            var_dump($pdostmt);
            var_dump($this->bind);
            return false;
        }
    }
```
This is the new error that appears:
`Notice: Undefined variable: pdostmt in /customers/a/d/5/domain.com/httpd.www/app/core/Model.php on line 61 NULL array(1) { [":id"]=> string(1) "1" } Warning: PDO::prepare(): SQLSTATE[00000]: No error: PDO constructor was not called in /customers/a/d/5/domain.com/httpd.www/app/core/Model.php on line 65 Fatal error: Call to a member function execute() on null in /customers/a/d/5/domain.com/httpd.www/app/core/Model.php on line 66 `

-----------------
That site is really cool and jam packed with great features! How long did that take to code and will you ever do a simple blog/login system as mini template almost for people to expand off of?

Thanks again!

**Comment by sonicsleuth** [comment]
Don't try to var_dump inside of an IF statement b/c it's trying to evaluate the result.
Wrong - if (var_dump($pdostmt->execute($this->bind) !== false))

Try doing before the IF statement this to see if a value is passed.
print_r($this->bind)

and this to see what the SQL looks like
print_r($this->sql)

Always try to capture the intended input before evaluation.

The PDO error on lines 63/64 might be cause because you are not passing in a value to the $SQl variable so the following cannot "prepare" the pdo statement...
  $pdostmt = $this->prepare($this->sql);

As for the sample site. It pretty huge, especially on the back end for the CMS.  It took a team of two engineers about 18-months which included working thru the business requirements from the stakeholder.

Will I build a basic BLOG scaffold using this MVC? ... In the short term probably not as a BLOG is a specific use case that can be built on this MVC.

**Comment by jackttcoms** [comment]
Ok here is the new result after doing print_r (this is much better than var dump)

`Warning: PDO::prepare(): SQLSTATE[00000]: No error: PDO constructor was not called in /customers/a/d/5/domain.com/httpd.www/app/core/Model.php on line 65 Array ( [:id] => 1 ) SELECT * FROM jh_users WHERE id = :id; Fatal error: Call to a member function execute() on null in /customers/a/d/5/domain.com/httpd.www/app/core/Model.php on line 68`

Also i have done a simple redirect helper but i need the full url/domain etc so is there a variable already set with that data otherwise i will just create my own! Like this: `define('FRONT_URL', 'https://domain.com');`
```
<?php
    /*
    * Helper url redirect
    */
    function redirect( $page ){
        header('location: ' . FRONT_URL . '/' . $page);
    }
```
Also regarding controllers and how with the url users/profile/1 etc if i remove the 1so you just get users/profile i get the missing argument and i know how to fix it but was wondering if you have something already built in or a more optimised way than how i am doing it below!
Here is my controller code:
```
    // Show our User Profile report
    public function profile($user_id = '')
    {
        if($user_id == ''){
            redirect('docs');
        }
        // Load the User Model so that we can query the database
        $user = $this->model('Users');
        // Get this user
        $bind = [':id' => $user_id];
        $data = $user->select('jh_users','id = :id', $bind);
        // Load the View passing to it the Users information as $data.
        $this->view('user/profile', $data);
        
    }
```

Yes and by blog, i do not mean full blown categories etc, i just mean a simple database add, edit, delete with form validation etc! When that is done people can understand/do pretty much anything! 

Thanks again! This MVC really is good from what i can see! Very thought out, has the functions i need and is very clean so when i transfer my marketplace script over to this MVC it should be great! Just need the database bit to work and then i'm all set :)

**Comment by sonicsleuth** [comment]
1. Redirect Helper - If you are just needing the current application URL use the global config setting $config['base_url'] found in /app/config/config.php otherwise if the domain is some other url building your own helper is correct.

2. Controllers - (A) In the event a required parameter is missing return a 404 page (or warning).  Generally speaking, you should validate the value exists before submitting it to the controller url, that is best practice when developing (never trust input from a human). (B) When you do receive a value for user_id in your example, you should also check if ANY record was returned before passing $data to the view - either to offer the view a default value (ie: user does not exist, etc). This is better than checking in within the View. Again, best practice there.

3. User DB Error - Try modifying the User Controller so that you create a new instance of the User Model and assign it to the $user property of the class User.

`class User extends Controller
{
    public $user;
    public function __construct()
    {
        $this->load_helper(['view']);
        $this->user = $this->model('Users');
    }

    public function profile($user_id = '')
    {
        if($user_id == ''){
            redirect('docs');
        }
        // Get this user
        $bind = [':id' => $user_id];
        $data = $this->user->select('jh_users','id = :id', $bind);
        // Load the View passing to it the Users information as $data.
        $this->view('user/profile', $data);
        
    }`

**Comment by jackttcoms** [comment]
Unfortunately none of that worked! I also tried a different host but i still get this error!

You can see for yourself here:
https://just-chewi-dev.000webhostapp.com/user/profile/test

```
connects
Warning: PDO::prepare(): SQLSTATE[00000]: No error: PDO constructor was not called in /storage/ssd3/167/5767167/public_html/app/core/Model.php on line 64
Array ( [:username] => test ) SELECT * FROM jh_users WHERE username = :username;
Fatal error: Uncaught Error: Call to a member function execute() on null in /storage/ssd3/167/5767167/public_html/app/core/Model.php:67 Stack trace: #0 /storage/ssd3/167/5767167/public_html/app/core/Model.php(120): Model->run('SELECT * FROM j...', Array) #1 /storage/ssd3/167/5767167/public_html/app/controllers/User.php(28): Model->select('jh_users', 'username = :use...', Array) #2 /storage/ssd3/167/5767167/public_html/app/core/App.php(86): User->profile('test', '') #3 /storage/ssd3/167/5767167/public_html/public/index.php(108): App->__construct(Array, Array) #4 {main} thrown in /storage/ssd3/167/5767167/public_html/app/core/Model.php on line 67
```

Would you like me to upload a .ZIP file with all the contents and you can see if im making a silly mistake?

Also for 2: I have not got to the check if exists part yet. I'm gonna get the DB working before i move onto that bit but im just saying a simple bit of code that is like if the id/argument is missing then redirect back to homepage or something so that i dont get this error!  `Warning: Missing argument 1 for User::profile() ` or `Fatal error: Uncaught ArgumentCountError: Too few arguments to function User::profile()`

Do you know a better way tho than how i have done it here like maybe the empty function or something?
```
    public function profile($user_id = '')
    {
        if($user_id == ''){
            redirect('docs');
        }
```

Thanks again! Once the db bit is working i will be on my merry way :)

**Comment by sonicsleuth** [comment]
Sure, attach a ZIP of your site and I will load it up locally and have a look.  Ensure the database connection is accepting all connection from anywhere as it needs to work on my server.

**Comment by jackttcoms** [comment]
Yes here is my version! Please let me know if im doing something really stupid.
Thanks in advance!

[mvc-bug.zip](https://github.com/sonicsleuth/mvc-framework-php/files/2006830/mvc-bug.zip)

**Comment by sonicsleuth** [comment]
In a nutshell here is how I modified your Controller and Model to make your implementation work.

I moved the query you had in the Controller over to the Model where it is best located (model = data).  The Controller now calls this User Model method and receives back the data.  This approach is cleaner and easier for unit testing too.

New Controller... Instantiate a new $user object for this Controller to use.  Then call the Users Model as shown. 

```
class User extends Controller
{
    public $user;

    public function __construct()
    {
        $this->load_helper(['view']);
        $this->user = $this->model('Users'); // Instantiate a new user object.
    }

    // Show our User Profile report
    public function profile($user_id)
    {
       // Get the user by id. (much cleaner)
        $data = $this->user->getUserByUserId($user_id);

        // Load the View passing to it the Users information as $data.
        $this->view('user/profile', $data);     
    }
}
```


The new Users Model method called upon by the User Controller (above)...

```
public function getUserByUserId($user_id)
    {
        $bind = [':username' => $user_id];
        $results = $this->db->select('jh_users','username = :username', $bind);

        return $results;
    }
```


I also commented off these Routes as they are not needed when the URL is /controller/method/param (ie: /user/profile/test) as a magic route.  These Route patterns are also buggy - meaning the first one /user/profile/test tries to return "profile" & "test" as params to the default user/index method.  Be careful how your routes "stack up".

```
//$route['user/([a-z]+)/([a-z]+)'] = 'home/user/$1/$2';
//$route['profile/([a-z]+)'] = 'user/profile/$1';
```

I also noticed a bug in the methods you wrote in your User Model where you did not "return" the $result (fix those too).

Enjoy.

**Comment by jackttcoms** [comment]
Please can you send me back the working files that you have edited because currently the error i get is:

```
Array ( [:username] => 1 ) SELECT * FROM jh_users WHERE username = :username; Warning: Invalid argument supplied for foreach() in /customers/a/d/5/domain.com/httpd.www/app/core/Controller.php on line 36 Warning: Invalid argument supplied for foreach() in /customers/a/d/5/domain.com/httpd.www/app/helpers/view.php on line 17
MVC Framework
Model View Controller Documentation
Warning: Invalid argument supplied for foreach() in /customers/a/d/5/domain.com/httpd.www/app/helpers/view.php on line 17

Author: Richard Soares

```

Thanks in advance! Its very odd! You are very helpful, i can see i'm the errors are almost over and then i can begin building my system.

Thanks again!

**Comment by sonicsleuth** [comment]
[mvc-bug-updated.zip](https://github.com/sonicsleuth/mvc-framework-php/files/2010345/mvc-bug-updated.zip)

Attached is your original MVC app with the correction I applied to make it work.  It fully works on my local LAMP server.  Anything beyond this I'm not sure how I can help as it does work locally for me.

Files Edited:
- /app/controllers/User.php
- /app/models/Users.php
- /app/config/routes.php

**Comment by jackttcoms** [comment]
Yes it works on all hosts i have tested except one.com! 

The error given is:
```
connectsArray ( [:username] => test ) SELECT * FROM jh_users WHERE username = :username; Warning: Invalid argument supplied for foreach() in /customers/a/d/5/domain.com/httpd.www/app/core/Controller.php on line 36 Warning: Invalid argument supplied for foreach() in /customers/a/d/5/domain.com/httpd.www/app/helpers/view.php on line 17
MVC Framework
Model View Controller Documentation
Current version is PHP 7.1.16 Warning: Invalid argument supplied for foreach() in /customers/a/d/5/domain.com/httpd.www/app/helpers/view.php on line 17

Author: Richard Soares
```

I'm currently getting the technicians to look at it and when/if they have a fix i will let you know also are you planning anything new for this MVC update wise?

Thanks again!

**Comment by jackttcoms** [comment]
All fixed! Thanks for being so helpful!
