### ISSUE TITLE
Fix CSS structure

### ISSUE THREAD

**Issue by jackttcoms** [sonicsleuth/mvc-framework-php#5]
Hi! Don't answer unless you have got back from holiday (probs not) but do you know how i could fix the indentation of the css stylesheets. As shown in the image below the bootstrap is inline but very the other stylesheets are not! Any suggestions? Thanks

![image](https://user-images.githubusercontent.com/26184209/40724821-e5a9d574-6419-11e8-96d7-576e4b6bde85.png)

**Comment by sonicsleuth** [comment]
Indentation does not affect the performance of the page, however, if you are simply looking to keep the source code neat you can do the following...

For every View file set the load_style() function flush left, meaning no whitespace, tabs, etc before the following PHP line:

`<?php load_style(['reset','prism','main']) ?>`

Then update the load_style() helper function located here: /app/helpers/view.php so that you are forcing a TAB in front of each css string line so they all indent equally, like so:

`echo "\t" . '<link rel="stylesheet" href="' . WEB_ROOT . 'css/' . $path . '.css" type="text/css" />' . "\r\n";`

**Comment by jackttcoms** [comment]
That's great thanks so much and i know this is only minor but is it possible to remove the gaps in between?

Thanks again!

![image](https://user-images.githubusercontent.com/26184209/40740794-abed4640-6441-11e8-9a3b-44bf21456d3c.png)

------------------------------

Also i have one final major question and its regarding MVC's in general! As i'm relatively new to them i'm wondering how i get data constantly from the database or how would i do it because basically in my db i have a table called 'settings' and it has 'title || Brand Name' in it so how would i get that title echoed on every page?

Do i do a helper or how do i get the entire settings database on hand ready for whenever i need it?

In my old code i used to do it like this - 
`    <title><?php echo $settings['title']; ?> - MVC Framework</title>`

Thanks again

-- Also here is a gif of what i have made so far using your brilliant framework :)
https://gyazo.com/c24c527f1529a834c96e1ff682d20225

**Comment by jackttcoms** [comment]
Quick question, i did not open a new issue as i feel its rather small but basically with my search form, its works great but when i do a search and no results show, it still counts it as 1 so is there a way to make it only in this circumstance to say 0 found?

Here is an image of no results:
![image](https://user-images.githubusercontent.com/26184209/42081673-f1d0c47c-7b7d-11e8-98d9-c9da9fbd8d9e.png)

Here is an image of 1 result returned:
![image](https://user-images.githubusercontent.com/26184209/42081727-170e7482-7b7e-11e8-83ec-687b122439b1.png)


Thanks

**Comment by sonicsleuth** [comment]
Only if 1+ records are returned will there be an array otherwise it will be bool FALSE.  You should be able to test for FALSE when no data is returned and provide the appropriate notice to the user.

`if($data == FALSE) { echo "No records found"; } `

**Comment by jackttcoms** [comment]
Maybe this would help:
```
    public function search()
    {
        if(!$_GET['term']){
            redirect('');
        }
        $getSearchTerm = $this->item->getSearchTerm('term');
        $getSettings = $this->setting->getAll();
        $getCategories = $this->setting->getCategories();
        $term = clean($_GET['term']);
        $getSearchResults = $this->item->getSearchResults($term);
        $count = count($getSearchResults);
        $data = [
            'getSettings' => $getSettings,
            'getCategories' => $getCategories,
            'title' => $term,
            'count' => $count,
            'getSearchResults' => $getSearchResults
        ];
        $this->view('search', $data);
    }
```

I think its because i'm counting this   `$count = count($getSearchResults);` but otherwise how do I echo the amount returned? Thanks

**Comment by sonicsleuth** [comment]
Assuming $getSearchResults is receiving either FALSE or an array of results
using the recently updated Model, I would just change this line of code
like so...

```
if( $getSearchResults == false) {
    $count = 0;
} else {
     $count = count($getSearchResults);
}
```

**Comment by jackttcoms** [comment]
Wow thanks Sonic, literally easiest thing i have ever done and don't know why i asked you but im very grateful and sorry for asking such a simple question :)
