### ISSUE TITLE
Here is the sample blog...

### ISSUE THREAD

**Issue by jackttcoms** [sonicsleuth/mvc-framework-php#7]
Hi Sonicsleuth! 

Here is a blog built on your MVC that you can check if you like and use as a demo. It only needs a pagination bit now so i was wondering whether you could do that but for this sample demo and then it can be used for educational demo purposes as it does CRUD and a bit more but let me know what you think and if i have done it correctly.

----------------------------------------------------------------
**Features:**
Add/Edit/Delete Posts
404/Error Checking
Form Validation
Bootstrap 4
Maybe Pagination

**If you wanted to expand:**
Image Upload instead of URLs
View Counter
Authentication

Thanks
------------------------------------------------------------------------------------
**Screenshots:**
![image](https://user-images.githubusercontent.com/26184209/41119360-895642ea-6a8a-11e8-9202-61473d4f069a.png)
![image](https://user-images.githubusercontent.com/26184209/41119441-b2256d72-6a8a-11e8-9a0d-cfce041382e2.png)
![image](https://user-images.githubusercontent.com/26184209/41119463-bf677c3c-6a8a-11e8-8a0e-ecd8ac360069.png)
![image](https://user-images.githubusercontent.com/26184209/41119560-fe614e36-6a8a-11e8-8ef2-6314a6c65532.png)
![image](https://user-images.githubusercontent.com/26184209/41119573-080a06f8-6a8b-11e8-887c-0b1d4f7a0e12.png)
**Demo Source Code:**
[blog.zip](https://github.com/sonicsleuth/mvc-framework-php/files/2081715/blog.zip)

**Comment by jackttcoms** [comment]
Really stupid question but...

Hi Sonic, for some reason i'm having difficulty doing the row count php function.

Usually i do it like this but this is for non-mvc pure php format:
```
$query = "select * from chewi_posts";  
$stmt = $conn->prepare( $query, array(PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL));  
$stmt->execute();  
echo $stmt->rowCount();  
```

but my question is how do i do it in your MVC as your query's go as follows...
```
        $results = $this->db->select('chewi_posts');
???????->rowCount();
        return ???????????
```

Or would you suggest i do a global one which is in the model.php file? Could be a nice enhancement? 
I can see already in your model.php you have this...               

```
} elseif (preg_match("/^(" . implode("|", array("delete", "update")) . ") /i", $this->sql)) {
                    return $pdostmt->rowCount(); // return records affected.
```

Thanks very much and sorry again for asking a stupid question but i'm still getting used to not writing the entire query out as shown in the first example. Its a terrible habit that i need to break as your method is much quicker but please help.

**Comment by sonicsleuth** [comment]
In the core Model, the delete and update queries return a "count" to provide feedback on the number of affected rows.  There is no magic method for the select query like ->rowCount(). You must do this using PHP after you get your results, like so..

```
$results = $this->db->select('chewi_posts');
$totalRows = count($results);
```

Side note... if you have very complex SQL queries, like multiple JOINS etc, you can directly access the run() method of the Model like so...

```
$sql = "select * from users u join permissions p on p.user.id = u.id";
$results = $this->run($sql);
```

**Comment by jackttcoms** [comment]
Thanks very much and did you get a chance to look at the blog.zip and whether or not it is all correct to be a sample for others wanting to use your framework?

And basically to count you simply do this and thanks for letting me know the bit about more complex queries as i will be using them soon for permissions so thanks v much!
```
    public function getRowCount()
    {
        $results = $this->db->select('chewi_posts');
        $totalRows = count($results);
        return $totalRows;
    }
```

I'm going to work on the pagination now but my question is please can you expand on what you mean by the 

> I would make a Helper function here /app/helpers/... that would isolate the Pagination computation you have in your Page Controller.

As with the helpers, its functions not public functions so please can you explain further how i should utilise the helper and then i can implement this into the blog for the sample bit etc.

Thanks again

**Comment by sonicsleuth** [comment]
The Blog you created thus far looks good. Nice work.

**About the Helper for Pagination.**  I simply meant you should refactor your current Method where you place the "pagination process" into a standalone function (ie: Helper).  The goal when writing any method of a Class is to have it read like a set of instructions by calling subfunctions. This also keeps in line with the DRY methodology. Here some sudo code...

```
public function getAllUsers() {
   $users = $this->Users->getAllUsers();
   $paginationValues = $this->paginationHelper($users);   // Helper returns the pagination settings.  
   // The above method is cleaner than doing the logic inline here.

   $data = [ $users, $pagainationSettings ];
   $this-view('users', $data);
}
```

**Comment by jackttcoms** [comment]
Yes please use the blog as a demo on here so no one else has to ask you so many questions :)

Also with the bigger sql queries would you 100% recommend i use the method below and with the bind param what would i do for those ones?
```
$sql = "select * from users u join permissions p on p.user.id = u.id";
$results = $this->run($sql);
```

Right now with my products im trying to get the category name from the cat_id from items table so I create a new model and then 

before model code:
```
    public function getUserProducts($user_id)
    {
        $bind = [':username' => $user_id];
        $results = $this->db->select('msi_items','status = 1 AND author_id = :username', $bind);
        if(!is_array($results[0])) {
            $new_results = array();
            array_push($new_results, $results);
            return $new_results;
        } else {
            return $results;
        }
    }
```
After model code:
```
    public function getUserProducts($user_id)
    {
        $bind = [':username' => $user_id];
        $sql = "SELECT * FROM msi_items
INNER JOIN msi_itemscat
ON msi_items.cat_id= msi_itemscat.id
WHERE msi_items.status = 1 AND msi_items.author_id = :username";
        $results = $this->run($sql);
        //$results = $this->db->select('msi_items','status = 1 AND author_id = :username', $bind);
        if(!is_array($results[0])) {
            $new_results = array();
            array_push($new_results, $results);
            return $new_results;
        } else {
            return $results;
        }
    }
```

Does the above look correct in your example of the more complex query? My example should show 'get all data from items and get the category name from the category table based on the category id from the items table'? So please let me know how i do the bind bit and if i have done the complex query correctly :)

Thanks

**Comment by sonicsleuth** [comment]
You pass the binding values the same way as with other methods. See the updated` run()` with a bind below.  

```
$bind = [":id" => 123];
$sql = "select * from users u join permissions p on p.user.id = u.id";
$results = $this->run($sql, $bind);
```

You might have to customize the name of your placeholders if there are conflicting column names, like an "id" in Users and Settings - do this like ":user_id" and ":settings_id"

**Comment by jackttcoms** [comment]
Thanks but i get this error for writing this code: 
```
        $bind = [':username' => $user_id];
        $sql = "SELECT msi_items.*, msi_itemscat.name FROM msi_items INNER JOIN msi_itemscat ON msi_items.cat_id= msi_itemscat.id WHERE msi_items.status = 1 AND msi_items.author_id = :username ";
        $results = $this->run($sql, $bind);
```
Here is what the error says:
`Warning: PDO::prepare(): SQLSTATE[00000]: No error: PDO constructor was not called in /customers/a/d/5/domain.com/httpd.www/app/core/Model.php on line 62 Fatal error: Uncaught Error: Call to a member function execute() on null in /customers/a/d/5/domain.com/httpd.www/app/core/Model.php:63 Stack trace: #0 /customers/a/d/5/domain.com/httpd.www/app/models/Users.php(62): Model->run('SELECT msi_item...', Array) #1 /customers/a/d/5/domain.com/httpd.www/app/controllers/User.php(249): Users->getUserProducts('1') #2 /customers/a/d/5/domain.com/httpd.www/app/core/App.php(86): User->profile('admin') #3 /customers/a/d/5/domain.com/httpd.www/public/index.php(134): App->__construct(Array, Array) #4 {main} thrown in /customers/a/d/5/domain.com/httpd.www/app/core/Model.php on line 63 `

Thanks

**Comment by sonicsleuth** [comment]
Sorry about that, I did not specify when calling run() that you are calling it from any one of your Models that your Controller has instantiated.  The Model you choose is not important as they all have access to the core run() method. Like so...

`$results = $this->users->run($sql, $bind); // this is calling run() from your Users model.`

**Comment by jackttcoms** [comment]
Thanks for the quick response but this is the error i get now, the model file name is Users.php and the class name is Users

Notice: Undefined property: Users::$users in /customers/a/d/5/domain.com/httpd.www/app/models/Users.php on line 64 Fatal error: Uncaught Error: Call to a member function run() on null in /customers/a/d/5/domain.com/httpd.www/app/models/Users.php:64 Stack trace: #0 /customers/a/d/5/domain.com/httpd.www/app/controllers/User.php(249): Users->getUserProducts('1') #1 /customers/a/d/5/domain.com/httpd.www/app/core/App.php(86): User->profile('admin') #2 /customers/a/d/5/domain.com/httpd.www/public/index.php(120): App->__construct(Array, Array) #3 {main} thrown in /customers/a/d/5/domain.com/httpd.www/app/models/Users.php on line 64 

This is my code:
```
    public function getUserProducts($user_id)
    {
        $bind = [':username' => $user_id];
      //  $results = $this->db->select('msi_items','status = 1 AND author_id = :username', $bind);
        $sql = "SELECT msi_items.*, msi_itemscat.name FROM msi_items INNER JOIN msi_itemscat ON msi_items.cat_id= msi_itemscat.id WHERE msi_items.status = 1 AND msi_items.author_id = :username ";
        $results = $this->users->run($sql, $bind);
        if(!is_array($results[0])) {
            $new_results = array();
            array_push($new_results, $results);
            return $new_results;
        } else {
            return $results;
        }
    }
```

Thanks

**Comment by jackttcoms** [comment]
and regarding the pagination, your method looks really cool but as im basically a manual person my brain is dying here! Please can you explain because right now i get the helper bit but then i dont get how you do the offset and limiter etc? Please could you do an example for the blog sample i sent you.

Right now this is where im at, I create a helper in the helper folder that does the calculations, i do that but doing a getall model bit but then im confused with how you return that result back to the controller so... 

This is your pseudo code:
```
public function getAllUsers() {
   $users = $this->Users->getAllUsers();
   $paginationValues = $this->paginationHelper($users);   // Helper returns the pagination settings.  
   // The above method is cleaner than doing the logic inline here.

   $data = [ $users, $pagainationSettings ];
   $this-view('users', $data);
}
```
Here is the model:
```
    public function getPosts()
    {
        $results = $this->db->select('msi_posts','status = 1');
        if(!is_array($results[0])) {
            $new_results = array();
            array_push($new_results, $results);
            return $new_results;
        } else {
            return $results;
        }
    }
```

Controller:
```
    public function index()
    {
        $this->load_helper(['paginationHelper']);
        $getPosts = $this->blog->getPosts();
        $paginationValues = $this->paginationHelper($getPosts); 
       $pagSettings ??????????????
        if(is_array($getPosts[0]) ) {
            $isPosts = true;
        } else {
            $isPosts = false;
        }
        $data = [
            'post' => $getPosts,
            'paginationSettings' => $pagSettings,
            'isPosts' => $isPosts
        ];
        if($getPosts == false) { redirect('error'); die(); }
        $this->view('blog/index', $data);
    }
```

Again thanks, i am slowly getting the hang of models and controllers and after the pagination i truly believe i can go it alone afterwards, this is my final obstacle but after this i will stop bothering you as i fear im doing.

Thanks so much again, I really appreciate it!

**Comment by sonicsleuth** [comment]
RE: using the `run()` method:
Change this...
`$results = $this->users->run($sql, $bind);`
to this...
`$results = $this->db->run($sql, $bind);`
and let me know if it clears up.

RE: Pagination Helper:
Your Pagination Helper should **enhance** the records you are paginating with other useful data.

Basically you want your `$getPosts` value to contain the "current" set of records, be that the first, next, or last set.  

But first, update your index Controller method to accept the values or set a default like so: index($offest=0, $limit=25) as you will always pass in those from pagination links I'd assume (ie: Controller/Method/offset/limit)

Using the offset and limit get your first or next or last set of records THEN hand off those records to your Helper.  

The Helper should only be anaylizing your found records to setup your next offset and limit values. 

The Helper returns an array containing the records you passed in (passthru), the new offset (new), and current limit (passthru).  

This associative array `$paginationValues` is a package of info about your records that you pass to the View and used like: `$paginationValues['posts']` (foreach loop), `$paginationValues['offset']` & `$paginationValues['limit']` (for pagination links).

Basic diagram:
found_records >> Helper returns (found_records, offset, limit) >> pagination_data_with_records >> use in View.

```
$getPosts = $this->blog->getPosts($offest, $limit);
$paginationValues = $this->paginationHelper($getPosts, $offest, $limit);

output:
paginationValues [
"offset" = 100,
"limit" = 25,
"posts" = $getPosts
]
```

**Comment by jackttcoms** [comment]
Hi, that worked great but can i ask you a silly question that is confusing me for some reason. Im doing a badge/achievement system and am currently using a foreach to get the dynamic badge data from the db but obviously that just echos all the data without any checking to see if the user has actually earned it so is there a way to do some kind of validation to say if($data['user']['am_exclusive'] = 1){ } or some fancy sql query to check if the user id has am_exclusive = 1 then show exclusive badge or if moderator = 1 then show moderator badge etc?

And regarding the helper, this bit here is a tad unclear to me: $this->paginationHelper, does this go in the controller because if so what about this $this->load_helper(['paginationHelper']);?? And is it something like this? The calculation bit in the function is the final bit im unsure on, what do you mean by Helper returns (found_records, offset, limit) like how does the helper return (sorry for sounding thick i'm just trying to get out of all my old poor coding habits and my brain is fighting change 👍 which needs to happen!)

And basically in the controller i do this but surely its $page=1 like this public function index($page=1) like my old bit of code?
```
    public function index($offest=0, $limit=15)
    {
       //// $this->load_helper(['paginationHelper']);
        $getPosts = $this->blog->getPosts($offest, $limit);
        $paginationValues = $this->paginationHelper($getPosts, $offest, $limit); 
        if(is_array($getPosts[0]) ) {
            $isPosts = true;
        } else {
            $isPosts = false;
        }
     $paginationValues= [
            'post' => $getPosts,
            'offset' => $offset,
            'limit' => $limit,
            'isPosts' => $isPosts
        ]; 
        if($getPosts == false) { redirect('error'); die(); }
        $this->view('blog/index', $paginationValues );
    }
```

In the model this:
```
    public function getPosts($offset, $limiter)
    {
        $bind = [':offset' => $offset, ':limiter' => $limiter];
        $results = $this->db->select('msi_posts','status = 1 ORDER BY id DESC LIMIT :offset, :limiter', $bind);
        if(!is_array($results[0])) {
            $new_results = array();
            array_push($new_results, $results);
            return $new_results;
        } else {
            return $results;
        }
    }
```

In the helper file:
```
function($getPosts, $offest, $limit) {
			// Page number
			$page = $page;
			// Number of items per page 
			$limit = $limitdynamic;
	  		$adjacents = 2;	
			// Get total rows
			$totalRows = $this->orderModel->getRowCount();
	  		// Compute total pages rounded up
	  		$totalPages = ceil($totalRows / $limit);
	  		// Compute for the offset
	        $offset = $limit * ($page-1);
	      	if($totalPages <= (1+($adjacents * 2))) {
	        	$start = 1;
	        	$end   = $totalPages;
	      	} else {
	        	if(($page - $adjacents) > 1) { 
	          		if(($page + $adjacents) < $totalPages) { 
	            		$start = ($page - $adjacents);            
	            		$end   = ($page + $adjacents);         
	          		} else {             
	            		$start = ($totalPages - (1+($adjacents*2)));  
	            		$end   = $totalPages;               
	         		}
	        	} else {               
	          		$start = 1;                                
	          		$end   = (1+($adjacents * 2));             
	        	}
	      	}
}
```

Thanks again very much! 💯
