### ISSUE TITLE
Advanced SQL Query and no items found error

### ISSUE THREAD

**Issue by jackttcoms** [sonicsleuth/mvc-framework-php#8]
Hi, a while back you told me about the array system where it checks if there are any items and if not echo the no items found but ever since i did the more complex query it no longer works!

```
    public function getFreeItems()
    {
        //$results = $this->db->select('msi_items','status = 1 AND free = 1');
        $sql = "SELECT msi_items.*, msi_itemscat.name AS catname FROM msi_items INNER JOIN msi_itemscat ON msi_items.cat_id = msi_itemscat.id WHERE msi_items.status = 1";
        $results = $this->db->run($sql);
        if(!is_array($results[0])) {
            $new_results = array();
            array_push($new_results, $results);
            return $new_results;
        } else {
            return $results;
        }
    }
```

When there are no items instead of the no items message i get this...
![image](https://user-images.githubusercontent.com/26184209/41401869-d4128c84-6fb8-11e8-9482-adf5a7522a78.png)

I'm pretty sure its the array bit but i'm unsure what i need to change 

Thanks again

**Comment by jackttcoms** [comment]
:/

**Comment by sonicsleuth** [comment]
The comments above the run() method of the base Model explain that using the run() method directly will return an Object, not an Array.  So you need to convert this object to an array in your controller.  Basically, the select() methods do this for you, however, the run() method is a dependency to all other query methods.  Read the PHP manual for how to convert an object to an array.

> _This method is used to run free-form SQL statements that can't be handled by the included delete, insert, select, or update methods. If no SQL errors are produced, this method will return the number of affected rows for DELETE, INSERT, and UPDATE statements, or an object of results for SELECT, DESCRIBE, and PRAGMA statements._

The PHP NOTICE you are getting is because there is nothing in the array to loop over, which is a result because as stated above, you need to update your code where using run() to convert an object to an array first.

**Comment by jackttcoms** [comment]
Thanks very much, do you mean something like this where you turn it into an array this way? Or am i taking the wrong approach.

From my knowledge to turn an object into an array you do this: `$arrayVariable = (array) $objectVariable; ` but now im stuck with what to do next? You said to do it in the controller but what about the array bit in the model. Could you please show me what you meant.

```
    public function getFreeItems()
    {
        //$results = $this->db->select('msi_items','status = 1 AND free = 1');
        $sql = "SELECT msi_items.*, msi_itemscat.name AS catname FROM msi_items INNER JOIN msi_itemscat ON msi_items.cat_id = msi_itemscat.id WHERE msi_items.status = 1 AND msi_items.free = 1";
        $results = $this->db->run($sql);
        if(!is_array($results[0])) {
            $new_results = array();
            array_push($new_results, $results);
            return $new_results;
        } else {
            return $results;
        }
    }
```

    public function index()
    {
        $getSettings = $this->setting->getAll();
        $freeItems = $this->item->getFreeItems();
        
        $array = (array) $freeItems;
        var_dump($array);
        if(is_array($array[0]) ) {
            $isFreeItems = true;
        } else {
            $isFreeItems = false;
        }
        
        $data = [
            'settings' => $getSettings,
            'freeItems' => $array,
            'isFreeItems' => $isFreeItems
        ];
        $this->view('index', $data);
    }


Thanks again very much

**Comment by sonicsleuth** [comment]
_FYI - I am slow in responding as I was in a bad car accident which totaled my vehicle so that I'm dealing with the insurance and replacement car shopping since last week. Liability was on the other guy. I survived ok, no worries._

Converting the object to an array could/should be done in the Model as you stated (it's clearer).  I mentioned the Controller as it is also possible for issues that might be outside some pattern.

You can cast the object to an array to get all its members as you are familiar with `(array) $object.`  To learn something more advanced have a look at [get_object_vars](http://php.net/manual/function.get-object-vars.php)

Anyhow... the change to your Model methods using run() is simple. Cast the object-to-array just before your normal checks, like so:

```
public function getFreeItems()
    {
        //$results = $this->db->select('msi_items','status = 1 AND free = 1');
        $sql = "SELECT msi_items.*, msi_itemscat.name AS catname FROM msi_items INNER JOIN msi_itemscat ON msi_items.cat_id = msi_itemscat.id WHERE msi_items.status = 1 AND msi_items.free = 1";
        $results_obj = $this->db->run($sql); // Updated var name.
        $results = (array) $results_obj; // Cast object to an array
        if(!is_array($results[0])) {
            $new_results = array();
            array_push($new_results, $results);
            return $new_results;
        } else {
            return $results;
        }
    }
```

**Comment by jackttcoms** [comment]
Sorry to hear about that, hope you recover well. It happened to me a few months ago, there really are some crap drivers on the road!

Anyway, the array bit of code that says 'nothing found' when there are no items returned is confusing me. Please can you show me what bit to edit now as i'm a tad confused as to whether i need to change the model bit of code or the controller bit of code. This functionality is a vital and pretty standard so please can you edit my code so that it works. Sorry to sound blunt but i'm getting frustrated with myself that i don't fully understand arrays which is a basic thing that I learned at the beginning but have forgotten along the way. I literally have not used arrays since using your MVC's so its a change and challenge for me but if you could show me what i am supposed to do it may help me understand it better.

Here is my controller code:
```
    public function favourites()
    {
        if(isset($_SESSION['uid'])){
        $getSettings = $this->setting->getAll();
        $getUserWishlist = $this->user->getUserWishlist($_SESSION['uid']);
        $getCategories = $this->setting->getCategories();
        if(is_array($getUserWishlist[0]) ) {
            $isWishlist = true;
        } else {
            $isWishlist = false;
        }
        if(is_array($getCategories[0]) ) {
            $isCategory = true;
        } else {
            $isCategory = false;
        }
        $data = [
            'title' => 'Favourites',
            'settings' => $getSettings,
            'wishlist' => $getUserWishlist,
            'isWishlist' => $isWishlist,
            'mainCategory' => $getCategories,
            'isCategory' => $isCategory
        ];
        $this->view('user/favourites', $data);
        } else {
			redirect('error');
		}
    }
```
Here is my model code:
```
    public function getUserWishlist($user_id)
    {
        $bind = [':user_id' => $user_id];
        $sql = 'SELECT msi_wishlists.*, msi_items_categories.name AS catname, msi_items.icon_img AS icon_img, msi_items.name AS name, msi_items.price AS price, msi_items.modified AS modified FROM msi_items INNER JOIN msi_wishlists ON msi_wishlists.item_id = msi_items.id INNER JOIN msi_items_categories ON msi_items_categories.id = msi_items.cat_id WHERE msi_items.status = 1 AND msi_wishlists.user_id = :user_id';
        $results = $this->db->run($sql, $bind);
        if( !is_array($results[0]) ) {
            $new_results = array();
            array_push($new_results, $results);
            return $new_results;
        } else {
            return $results;
        }
    }
```

Here is my view code:
```
                <?php if($data['isWishlist']) { foreach($data['wishlist'] as $wishlist) : ?>
                    <div class="d-flex relative align-items-center p-3 mb-3 text-black bg-white rounded shadow-1 item">
                        <a href="<?php echo FULL_ROOT;?>/item/<?php echo $wishlist['item_id']; ?>/"><img width="100" class="img-fluid rounded mr-4" src="<?php echo FULL_ROOT;?>/uploads/items/<?php echo $wishlist['item_id']; ?>/<?php echo $wishlist['icon_img']; ?>" alt="<?php echo $wishlist['name']; ?>"></a>
                        <div class="lh-100">
                            <h4 class="mb-0 lh-100"><?php echo $wishlist['name']; ?>-<?php echo $wishlist['catname']; ?></h4>
                            <small>Price: <span class="badge badge-secondary bg-1 align-text-center"><?php echo $data['settings']['payment_currency_sym']; ?><?php echo $wishlist['price']; ?></span> | Last Updated: <span class="badge badge-secondary bg-1 align-text-center"><?php echo helper_format_date_3($wishlist['modified']); ?></span></small>               
                             <div class="clearfix mt-2">
                                    <a href="<?php echo FULL_ROOT;?>/item/<?php echo $wishlist['item_id']; ?>/" class="btn btn-sm btn-light float-left btn-lightb mr-2">Buy Now</a>
                                    <button data-hold="<?php echo $wishlist['id']; ?>" title="Remove" type="button" class="delete btn btn-sm btn-light float-left btn-lightb"><i class="fas fa-trash-alt"></i></button>
                                </div>
                        </div>
                    </div>
                <?php endforeach; } else { ?>
                <div class="col-12"><div class="alert alert-primary shadow-1" role="alert">
                    <b><i class="fas fa-info-circle"></i> Wishlist Empty!</b>
                </div></div>
                <?php } ?>
```

**Comment by sonicsleuth** [comment]
Think of the Model as responsible for "getting" data.  The Controller is responsible for "what should I do with these results".  Therefore I would update your controller as shown below which checks to see if the returned data even exists (not false) in your code case. 

We use the controller because you might want to "branch" off to another View if some data was not found.. but in this case you are accounting for the true/false in your View (that's ok too).

```
public function favourites()
    {
        if(isset($_SESSION['uid'])){
        $getSettings = $this->setting->getAll();
        $getUserWishlist = $this->user->getUserWishlist($_SESSION['uid']);
        $getCategories = $this->setting->getCategories();
        if(is_array($getUserWishlist[0]) || $getUserWishlist != false) {
            $isWishlist = true;
        } else {
            $isWishlist = false;
        }
        if(is_array($getCategories[0])  || $getCategories != false) {
            $isCategory = true;
        } else {
            $isCategory = false;
        }
        $data = [
            'title' => 'Favourites',
            'settings' => $getSettings,
            'wishlist' => $getUserWishlist,
            'isWishlist' => $isWishlist,
            'mainCategory' => $getCategories,
            'isCategory' => $isCategory
        ];
        $this->view('user/favourites', $data);
        } else {
			redirect('error');
		}
    }
```

To simplify the thought process here is an example Controller method where I am checking to see if any results came back when looking up my User by their private PIN id.  It's a test that dumps the findings and dies if no records were found.

```
public function pin($pin)
    {
        $data = $this->user->getByPin($pin);

        if($data === false) {
            die("No Records Found");
        }
        print_r($data);
    }
```

**Comment by jackttcoms** [comment]
Oh sorry i feel like I was not clear, im not talking about dying, i'm talking about the foreach and when there are no items returning then echo No Items Found.

Ok so this is my view file called favourites for ajax favourites which I got working fine but when there are no items in the user favourites it needs to return a message saying 'No items in Favourites'

Here is the screenshot of the error:
![image](https://user-images.githubusercontent.com/26184209/41654082-30f16a80-7480-11e8-9959-6a4060ceb909.png)


Here is my view code:
```
      <input type='hidden' name='token' value='<?php echo $_SESSION['utoken']; ?>' />
                <?php if($data['isWishlist']) { foreach($data['wishlist'] as $wishlist) : ?>
                    <div class="d-flex relative align-items-center p-3 mb-3 text-black bg-white rounded shadow-1 item">
                        <a href="<?php echo FULL_ROOT;?>/item/<?php echo $wishlist['item_id']; ?>/"><img width="100" class="img-fluid rounded mr-4" src="<?php echo FULL_ROOT;?>/uploads/items/<?php echo $wishlist['item_id']; ?>/<?php echo $wishlist['icon_img']; ?>" alt="<?php echo $wishlist['name']; ?>"></a>
                        <div class="lh-100">
                            <h4 class="mb-0 lh-100"><?php echo $wishlist['name']; ?></h4>
                            <small>Price: <span class="badge badge-secondary bg-1 align-text-center"><?php echo $data['settings']['payment_currency_sym']; ?><?php echo $wishlist['price']; ?></span> | Last Updated: <span class="badge badge-secondary bg-1 align-text-center"><?php echo helper_format_date_3($wishlist['modified']); ?></span> | Category: <span class="badge badge-secondary bg-1 align-text-center"><?php echo $wishlist['catname']; ?></span></small>
                             <div class="clearfix mt-2">
                                    <a href="<?php echo FULL_ROOT;?>/item/<?php echo $wishlist['item_id']; ?>/" class="btn btn-sm btn-light float-left btn-lightb mr-2">Buy Now</a>
                                    <button data-hold="<?php echo $wishlist['id']; ?>" title="Remove" type="button" class="delete btn btn-sm btn-light float-left btn-lightb"><i class="fas fa-trash-alt"></i></button>
                                </div>
                             
                        </div>
                    </div>
                <?php endforeach; } else { ?>
                <div class="col-12"><div class="alert alert-primary shadow-1" role="alert">
                    <b><i class="fas fa-info-circle"></i> Favourites Empty!</b>
                </div></div>
                <?php } ?>
```

So my controller code:
```
    public function favourites()
    {
        if(isset($_SESSION['uid'])){
        $getSettings = $this->setting->getAll();
        $getUserWishlist = $this->user->getUserWishlist($_SESSION['uid']);
        $getCategories = $this->setting->getCategories();
        if(is_array($getUserWishlist[0]) || $getUserWishlist != false) {
            $isWishlist = true;
        } else {
            $isWishlist = false;
        }
        if(is_array($getCategories[0])  || $getCategories != false) {
            $isCategory = true;
        } else {
            $isCategory = false;
        }
        $data = [
            'title' => 'Favourites',
            'settings' => $getSettings,
            'wishlist' => $getUserWishlist,
            'isWishlist' => $isWishlist,
            'mainCategory' => $getCategories,
            'isCategory' => $isCategory
        ];
        $this->view('user/favourites', $data);
        } else {
			redirect('error');
		}
    }
```


And my model code is:
```
    public function getUserWishlist($user_id)
    {
        $bind = [':user_id' => $user_id];
        $sql = 'SELECT msi_wishlists.*, msi_items_categories.name AS catname, msi_items.icon_img AS icon_img, msi_items.name AS name, msi_items.price AS price, msi_items.modified AS modified FROM msi_items INNER JOIN msi_wishlists ON msi_wishlists.item_id = msi_items.id INNER JOIN msi_items_categories ON msi_items_categories.id = msi_items.cat_id WHERE msi_items.status = 1 AND msi_wishlists.user_id = :user_id';
        $results = $this->db->run($sql, $bind);
        if( !is_array($results[0]) ) {
            $new_results = array();
            array_push($new_results, $results);
            return $new_results;
        } else {
            return $results;
        }
    }
```



So its to do with the array and the fact that i'm directly using the run() function so it does not turn it into an array like if it was the select() so i have to do it myself but my problem is where do i convert it into an array so please can you edit my code above to do just that. Thanks.

Your help is much appreciated and i really want to thank you for taking time out of your day to help me .

**Comment by jackttcoms** [comment]
Regarding sessions, do you know any good php classes that basically make it so that if i update a user setting from the admin, it automatically updates on the users session also?

Thanks

**Comment by sonicsleuth** [comment]
Try this...

```
public function getUserWishlist($user_id)
    {
        $bind = [':user_id' => $user_id];
        $sql = 'SELECT msi_wishlists.*, msi_items_categories.name AS catname, msi_items.icon_img AS icon_img, msi_items.name AS name, msi_items.price AS price, msi_items.modified AS modified FROM msi_items INNER JOIN msi_wishlists ON msi_wishlists.item_id = msi_items.id INNER JOIN msi_items_categories ON msi_items_categories.id = msi_items.cat_id WHERE msi_items.status = 1 AND msi_wishlists.user_id = :user_id';
        $results = $this->db->run($sql, $bind);
        if($results === false) { // if nothing is returned make force $results into an array.
            $results = array();
        }
        if( !is_array($results[0]) ) {
            $new_results = array();
            array_push($new_results, $results);
            return $new_results;
        } else {
            return $results;
        }
    }
```

RE: Auto-Sessions library. You could write a Model to manage your sessions. Then when your controller has methods requireing session updates you include your Sessions Model method calls.  How this Sessions Model class works will beup to you but give you a single point of control.  Sessions are just another type of data for a Model to handle.

**Comment by jackttcoms** [comment]
Wow, i never thought using the run function directly would be so difficult but that also did not work :(
Its very confusing and odd tbh, i can see exactly what you are doing and it makes perfect sense yet its not working for some reason.

Do i need to change anything in the controller maybe?
```
    public function favourites()
    {
        if(isset($_SESSION['uid'])){
        $getSettings = $this->setting->getAll();
        $getUserWishlist = $this->user->getUserWishlist($_SESSION['uid']);
        $getCategories = $this->setting->getCategories();
        if(is_array($getUserWishlist[0]) || $getUserWishlist != false) {
            $isWishlist = true;
        } else {
            $isWishlist = false;
        }
        if(is_array($getCategories[0])  || $getCategories != false) {
            $isCategory = true;
        } else {
            $isCategory = false;
        }
        $data = [
            'title' => 'Favourites',
            'settings' => $getSettings,
            'wishlist' => $getUserWishlist,
            'isWishlist' => $isWishlist,
            'mainCategory' => $getCategories,
            'isCategory' => $isCategory
        ];
        $this->view('user/favourites', $data);
        } else {
			redirect('error');
		}
    }
```

Because right now this bit of code here is what checks if there is only one item in the array and prevents the error.
```
        if( !is_array($results[0]) ) {
            $new_results = array();
            array_push($new_results, $results);
            return $new_results;
        } else {
            return $results;
        }
```
And this controller bit of code is the bit that checks the array for a return or no return
```
        if(is_array($getUserWishlist[0]) || $getUserWishlist != false) {
            $isWishlist = true;
        } else {
            $isWishlist = false;
        }
```

Maybe, in the core/model do something where it is like if you directly call the run function then do the array bit there like you do with the select because this feature is quite necessary in my opinion as most people use complex queries.

Thanks

**Comment by sonicsleuth** [comment]
Only the Select method needs to check if there are 1+ or no records which happens to be why this check does not exist directly in the Run method (it's a higher order need).  The run() method of the base Model is shared by the Select, Insert, Delete methods.  

Calling the Run method directly for more complex SQL statements is a "hack" requiring you to add whatever data checks you need.  You could borrow the check from the base Model Select and incorporate it into your Model method. Basically, you are giving your "complex select" method the same functionality as the base Select, for example...

```
public function myComplexSql($id)
{
       $sql = "select ......  complex .... statement where id = :id join other tables ... etc";
       $bind = [
            ':id' => $id
        ]; 
       $data = $this->db->run($sql, $bind);

      // borrow the following from the Base Select method...
       if(empty($data)) {
            return false;
        } elseif (count($data) > 1) {
            return $data; // return full index of records.
        } else {
            return $data[0]; // return single record.
        }
}
```

Why is calling the run() method a "hack"?  -- The base Model is a lightweight ORM which means you typically do not write single "complex" sql statements as they can introduce bugs.  For example, you would first select() your users, then loop over them and query matching "preferences", adding only those needed columns to a master object (or array). However, I left the run() method public for classical query calls.

**Comment by jackttcoms** [comment]
Yes that worked until there is only one item left :( then i get the undefined offset error again! Is there any way in the core/model.php to do an advanced method just because using advanced complex statements is a basic part of coding so it really limits the MVC if you can't use complex queries as it prevents you to do the foreach checker or one item checker etc.

Current Issues (only occur when use complex queries):

- When doing complex queries it does not put it into an array unlike using the select method etc.
- When foreach returns nothing it does not show the 'Empty Message' instead shows the code inside the foreach just with no data.
- When foreach only returns one item it does not show up and you get undefined offset.


Thanks very much.

**Comment by sonicsleuth** [comment]
I have updated MVC repository with a new Model method to handle complex SQL statements called `selectExtended()`.  I have also updated the preexisting `select()` method so that a single record is now returned as a nested array vs an arrray itself - this will improve looping thru records.

Both of these base Model methods will now return:
- $results = array(array()) for 1 or more records
- FALSE if no records found - you can then test for this before runing your foreach loop.

You can pull in the repository again or add the following updates to the base Model class of the MVC.

Add to your base Model of the MVC.
```
/**
     * @param string $sql
     * @param string $bind
     * @param bool $entity_decode
     * 
     * Use this method when complex SQL statements are required, like table JOINS, are required.
     * 
     * Example:
     * $sql = "select * from users u join preferences p on p.user_id = u.id where p.role = :role ";
     * $bind = array (':role' => 'admin');
     * $results = $this->db->selectExtended($sql, $bind);
     * 
     * Note: HTML Entities returned from the database will be decoded by default. Set $entity_decode = false otherwise.
     */
    public function selectExtended($sql, $bind = "", $entity_decode = true)
    {
        $data = $this->run($sql, $bind, $entity_decode);

        if(empty($data)) {
            return false;
        } elseif (count($data[0]) > 1) {
            return $data; // return full index of records.
        } else {
            return $data[0]; // return single record.
        }

    }
```

Replace the current `select()` method of the base Model with this

```
public function select($table, $where = "", $bind = "", $fields = "*", $entity_decode = true)
    {
        $sql = "SELECT " . $fields . " FROM " . $table;
        if (!empty($where))
            $sql .= " WHERE " . $where;
        $sql .= ";";

        $data = $this->run($sql, $bind, $entity_decode);

        if(empty($data)) {
            return false;
        } elseif (count($data[0]) > 1) {
            return $data; // return full index of records.
        } else {
            return $data[0]; // return single record.
        }

    }
```
