### ISSUE TITLE
After update, lots broken now.

### ISSUE THREAD

**Issue by jackttcoms** [sonicsleuth/mvc-framework-php#9]
Hello, 

Thanks for doing the update but there is a bug which i have no clue how to fix! Basically i tired this bit of code ages ago but i then got lots of different problems so basically the blog worked great but then when i tried to login i got an error which is then fixed when i change the code back to this.
```
    public function select($table, $where = "", $bind = "", $fields = "*", $entity_decode = true)
    {
        $sql = "SELECT " . $fields . " FROM " . $table;
        if (!empty($where))
            $sql .= " WHERE " . $where;
        $sql .= ";";

        $data = $this->run($sql, $bind, $entity_decode);

        if(empty($data)) {
            return false;
        } elseif (count($data) > 1) {
            return $data; // return full index of records.
        } else {
            return $data[0]; // return single record.
        }
    }
```

instead of...
```
    public function select($table, $where = "", $bind = "", $fields = "*", $entity_decode = true)
    {
        $sql = "SELECT " . $fields . " FROM " . $table;
        if (!empty($where))
            $sql .= " WHERE " . $where;
        $sql .= ";";

        $data = $this->run($sql, $bind, $entity_decode);

        if(empty($data)) {
            return false;
        } elseif (count($data[0]) > 1) {
            return $data; // return full index of records.
        } else {
            return $data[0]; // return single record.
        }
    }
```

Would i be able to send you my sample project code for you to take a look at because maybe im doing something that works with how i used to do it but not with your MVC and you test out the foreach thing as well etc.?

Thanks very much and once i have got these bumps sorted I'd love to donate some kind of money to you because of how helpful you have been so far.

**Comment by jackttcoms** [comment]
If agreed then the login is admin@admin.com / password but as we have done this bit of code: `} elseif (count($data[0]) > 1) {` it breaks it and also individual post and edit post no longer works but as soon as i remove the [0] it works so yes if possible please take a look, it may help you find a fix quicker.
[testproject.zip](https://github.com/sonicsleuth/mvc-framework-php/files/2131317/testproject.zip)

**Comment by sonicsleuth** [comment]
This is just a bug fix which is breaking your code because your code is still "compensating" for the bug.  Not your fault... but a change to the MVC to correct this issue so it works better.

The bit of code you reference from the Model `select()` function ...  `(count($data[0]) > 1)` ... fixed a bug.  Your current code was (is) compensating for this bug.  Therefore you need to update your code for this update (it's not backward compatible).

This bug fix makes the results of a query have only two replies now.  
1) an array containing a list of 1+ records.  
2) a bool FALSE if no data found. 

What is probably happening in your code is that you are still dependent on a "single record" returning as a single index of values.  For example:

```
DEPRECIATED:  array( 'fname' => 'robert', 'lname' => 'smith' );
NEW: array( array( 'fname' => 'robert', 'lname' => 'smith' ) );
```

The new method makes it easier to loop thru 1 or more records now because there is a consistency with how the results are returned for both cases.  For example:

```
Single Record: 
array( 
    array( 'fname' => 'robert', 'lname' => 'smith' ) 
);

Multiple Records: 
array( 
   array( 'fname' => 'robert', 'lname' => 'smith' ),
   array( 'fname' => 'peter', 'lname' => 'north' ),
);
```

Perhaps the above helps you understand what you need to update.  Otherwise, send me your source code for review.

**Comment by jackttcoms** [comment]
ah ok, so please can you point out what needs to change here to fix individual post viewing.
```
    public function getPostById($id)
    {
        $bind = [':id' => $id];
        $results = $this->db->select('chewi_posts','id = :id',$bind);
        return $results;
    }
```

The foreach now works great with the complex queries so thanks but can you quickly confirm i am doing it right :)

Model
```
    public function getPosts()
    {
        $sql = "SELECT chewi_posts.*, chewi_users.name AS username FROM chewi_posts INNER JOIN chewi_users ON chewi_posts.author_id = chewi_users.id WHERE chewi_posts.status = 1";
        $results = $this->db->selectExtended($sql);
        
        if( !is_array($results[0]) ) {
            $new_results = array();
            array_push($new_results, $results);
            return $new_results;
        } else {
            return $results;
        }
    }
```
Controller
```
    public function index()
    {
        $getPosts = $this->blog->getPosts();
        $total = $this->blog->getRowCount();
        if(is_array($getPosts[0]) ) {
            $isPosts = true;
        } else {
            $isPosts = false;
        }
        $data = [
            "getPosts" => $getPosts,
            "isPosts" => $isPosts,
            "total" => $total
        ];
        $this->view('home', $data);
    }
```
View
```
                <?php if($data['isPosts']) { foreach($data['getPosts'] as $post) : ?>

                    <div class="col-lg-4 col-md-4 col-sm-6 mb-3">
                        <div class="card h-100 shadow-1">
                            <a href="<?php echo FULL_ROOT;?>/post/<?php echo $post['id']; ?>/">
                                <img class="card-img-top" src="<?php echo $post['image']; ?>" alt="<?php echo $post['title']; ?>">
                            </a>
                            <div class="card-body text-center">
                                <a href="<?php echo FULL_ROOT;?>/post/<?php echo $post['id']; ?>/"><h2 class="card-title font-weight-bold f-18"><?php echo $post['title']; ?>-<?php echo $post['username']; ?></h2></a>
                            </div>
                        </div>
                    </div>

                <?php endforeach; } else { ?>
                
                    <div class="col-12"><div class="alert alert-primary shadow-1" role="alert">
                        <b><i class="fas fa-info-circle"></i> Blog Empty!</b>
                    </div></div>
                
                <?php } ?>
```

Thanks

**Comment by sonicsleuth** [comment]
I explain in each section what (and why) my changes were made. (dbl check as I wrote this freehand here).

**MODEL**
The updated `select()` and `selectExtended()` methods will return an array collection of records for 1+ records OR just FALSE.  You no longer need to adjust the results for a single record, simply return the results.  In the VIEW we will check if there are any records.

```
public function getPosts()
    {
        $sql = "SELECT chewi_posts.*, chewi_users.name AS username FROM chewi_posts INNER JOIN chewi_users ON chewi_posts.author_id = chewi_users.id WHERE chewi_posts.status = 1";

        $results = $this->db->selectExtended($sql);

         return $results;
        }
    }

```

**CONTROLLER**
No need to confirm there are records and set a separate bool flag for use in your VIEW from within the Controller. It's best to check for records (or none) where you are using them, like the VIEW.

```
public function index()
    {
        $getPosts = $this->blog->getPosts();
        $total = $this->blog->getRowCount();

        $data = [
            "getPosts" => $getPosts,
            "total" => $total
        ];

        $this->view('home', $data);
    }
```

**VIEW**
Because `$data['getPosts']` will either be FALSE (no records) or NOT FALSE having 1+ records you can simply check for FALSE and display the "empty" message or proceed to loop thru the records.

_General good coding practice... it is always better to check for a NEGATIVE (ie: false, zero, none, empty) value before processing the expected POSITIVE result.  This will force you to think about what to do when the expected results are not there._

```
<?php if( $data['getPosts'] == FALSE ) { ?>

          <div class="col-12"><div class="alert alert-primary shadow-1" role="alert">
                <b><i class="fas fa-info-circle"></i> Blog Empty!</b>
           </div></div>

<?php } else {   foreach($data['getPosts'] as $post) : ?>

          <div class="col-lg-4 col-md-4 col-sm-6 mb-3">
                        <div class="card h-100 shadow-1">
                            <a href="<?php echo FULL_ROOT;?>/post/<?php echo $post['id']; ?>/">
                                <img class="card-img-top" src="<?php echo $post['image']; ?>" alt="<?php echo $post['title']; ?>">
                            </a>
                            <div class="card-body text-center">
                                <a href="<?php echo FULL_ROOT;?>/post/<?php echo $post['id']; ?>/"><h2 class="card-title font-weight-bold f-18"><?php echo $post['title']; ?>-<?php echo $post['username']; ?></h2></a>
                            </div>
                        </div>
                    </div>

<?php endforeach;  } ?>

```

**Comment by jackttcoms** [comment]
Sorry i don't think I explained that very well. When i go to the domain.com/post/1/ it does not work.

Here is the code that is responsible for it: 
```
    public function getPostById($id)
    {
        $bind = [':id' => $id];
        $results = $this->db->select('chewi_posts','id = :id',$bind);
        return $results;
    }
```
```
    public function post($id = '')
    {
        if($id == '') { redirect(''); }
        $data = $this->blog->getPostById($id);
        if($data === false) { redirect('error'); die();}
        $this->view('post', $data);     
    }
```

Here is an image of the error:
![image](https://user-images.githubusercontent.com/26184209/41912991-1a2a5c22-7948-11e8-85c1-85487daea427.png)

And with the login side, please can you look at that also because when i attempt to login it does not accept the password and says Notice: Undefined index: password in /customers/a/d/5/domain.com/httpd.www/testproject/app/models/Users.php on line 16 so am i supposed to do it a different way as when the data[0] is added it does not like it.

Here is the model code:
```
    public function login($email,$password)
    {
        $bind = [':email' => $email];
        $results = $this->db->select('chewi_users','email = :email', $bind);
        $hashed_password = $results['password'];
        if ( password_verify($password,$hashed_password) ) {
            return $results;
        } else {
            return false;
        }
    }
```

Thanks

**Comment by sonicsleuth** [comment]
1. What value are you getting from `$data = $this->blog->getPostById($id);`

2. The first notice/error you are showing is an "undefined index" for `getCategories` in your `header.php` file.  Is that value also part of the results of `$data` ? Seems like it's a bug elsewhere.

**Comment by jackttcoms** [comment]
im getting all the data from the db table associated with the id.

**Comment by jackttcoms** [comment]
so if id = 2 then it should get all this data: 
![image](https://user-images.githubusercontent.com/26184209/41927670-c2d0e41e-796a-11e8-83df-542f75fb4d05.png)

**Comment by sonicsleuth** [comment]
Can you dump the $data array and show it here for my review. I want to make sure the format is correct.

**Comment by jackttcoms** [comment]
Model:
```
    public function getPostById($id) //Does not work :(
    {
        $bind = [':id' => $id];
        $results = $this->db->select('chewi_posts','id = :id',$bind);
        return $results;
    }
```

Controller:
```
    public function index()
    {
        $getPosts = $this->blog->getPosts();
        $getCategories = $this->blog->getCategories();
        $total = $this->blog->getRowCount();
        $data = [
            "getPosts" => $getPosts,
            "getCategories" => $getCategories,
            "total" => $total
        ];
        $this->view('home', $data);
    }
```

Here is the var dump:
`string(2) "11" ["title"]=> string(6) "ddwwdw" ["content"]=> string(12) "efffwefewwff" ["published"]=> string(19) "2018-06-25 07:58:06" ["last_updated"]=> string(19) "2018-06-25 07:58:06" ["image"]=> string(79) "https://img.grouponcdn.com/deal/haYUX3UW3TUDJfhpnZsj/mu-960x582/v1/c700x420.jpg" ["status"]=> string(1) "1" ["author_id"]=> string(1) "1" } } `

**Comment by jackttcoms** [comment]
It vardumps all the correct data but im unable to show it when i do $data['title'] etc. like my view code:
```

    <!-- Page Content -->
    <div class="container">
        <div class="card">
            <div class="card-body">
                <img src="<?php var_dump($data); echo $data['image'];?>">
                <br>
                Title: <?php echo $data['title'];?>
                HTML Content: <?php echo $data['content'];?>
                Date Published: <?php echo $data['published'];?>
                Date Last Updated: <?php echo $data['last_updated'];?>
            </div>
        </div>
    </div>
```

but can i just quickly point out, it is fixed when you go to the core/model and change the data[0] back to $data but then it messes up the foreach thing again.

**Comment by sonicsleuth** [comment]
You need to change `$data['title']` to `$data[0]['title']` in your VIEW because the recent core Model updates now place all records, including a single record, as an indexed array of $data.  

If you do a `print_r($data)` you will better understand the nesting of the arrays on the `$data` variable. Similar to this:
```
Array ( 
   [0] => Array ( [fname] => Bob [lname] => Smith ) // $data[0]['fname'] = "Bob"
)
```

However, Update the following files replacing these functions as shown.  Once done, when you have a single record in $data it will auto-magically create php vars for each index name with it's value. Then you can do this shortcut.

A single Record in $data
```
Array ( 
   [0] => Array ( [fname] => Bob [lname] => Smith ) // $data[0]['fname'] = "Bob"
)
```
Use and output: 
```
echo $fname;  // = Bob
echo $lname;  // = Smith
```

**UPDATE THE FOLLOWING...**

**/app/helpers/view.php**
```
function extend_view($paths, $data)
{
    // Set each index of data to its named variable.
    if( is_array($data[0]) ) {
        foreach($data[0] as $key => $value) {
            $$key = $value;
        }
    }

    foreach ($paths as $path) {
        include (VIEWS_PATH . $path . '.php');
    }
}
```

**/app/core/Controller.php**
```
protected function view($view, $data = [])
    {
        if(file_exists(VIEWS_PATH . $view . '.php'))
        {
            // Set each index of data to its named variable.
            if( is_array($data[0]) ) {
                foreach($data[0] as $key => $value) {
                    $$key = $value;
                }
            }
            require_once VIEWS_PATH . $view . '.php';
        } else {
            return false;
        }
    }
```

**Comment by jackttcoms** [comment]
Ok thanks that worked and should the $$ be removed? or is that so that the $title can work?

**Comment by jackttcoms** [comment]
Also how would it work if i did it like this:

```
    public function post($id = '')
    {
        if($id == '') { redirect(''); }
        $getPostById = $this->blog->getPostById($id);
        $getCategories = $this->blog->getCategories();
        $data = [
            "post" => $getPostById,
            "getCategories" => $getCategories,
            "total" => $total
        ];
        if($getPostById === false) { redirect('error'); die();}
        $this->view('post', $data);     
    }
```

the $title would not longer in the view so would it be like this `<?php echo $data['post']['title'];?>` or `<?php echo $data[0]['post']['title'];?>` etc. btw both do not work

**Comment by sonicsleuth** [comment]
Good to here.

No keep the $$.  That is a PHP feature. It allows you to make a variable from the value of a variable. For example:

```
$var = "new_user"
$$var = "Robert"
echo $new_user; // output "Robert"
```

**Comment by jackttcoms** [comment]
And this is the array response:  `array(1) { [0]=> array(8) { ["id"]=> string(2) "11" ["title"]=> string(6) "ddwwdw" ["content"]=> string(12) "efffwefewwff" ["published"]=> string(19) "2018-06-25 07:58:06" ["last_updated"]=> string(19) "2018-06-25 07:58:06" ["image"]=> string(79) "https://img.grouponcdn.com/deal/haYUX3UW3TUDJfhpnZsj/mu-960x582/v1/c700x420.jpg" ["status"]=> string(1) "1" ["author_id"]=> string(1) "1" } }`

when the controller is like this:
```
    public function post($id = '')
    {
        if($id == '') { redirect(''); }
        $getPostById = $this->blog->getPostById($id);
        $getCategories = $this->blog->getCategories();
        $data = [
            "post" => $getPostById,
            "getCategories" => $getCategories,
            "total" => $total
        ];
        if($getPostById === false) { redirect('error'); die();}
        $this->view('post', $data);     
    }
```

so how do i echo this in the view?

**Comment by sonicsleuth** [comment]
RE: Also how would it work if i did it like this:

In this case, you are manually building up mixed values for the $data variable, strings, arrays, etc.  You need to call `getCategories` from `$data` like so.  It's all up to you when you pack $data manually.

Multiple Records:
`foreach( $data['getCategories'] as $record) ...`

Single Record:
`$data['getCategories'][0]`

**Comment by jackttcoms** [comment]
ooohhhh thanks very much, I got the [0] the wrong way around! `<?php echo $data['post'][0]['title']; ?>` and can i ask you if you are available for hire to do a simple pagination function as I can't get my head around it. but I see what you mean as i used your logic to build a unlimited categories and subcategories tree system. £

Thanks again, i think i am out of all the error zone now and can build my mini script for my school project :)

**Comment by jackttcoms** [comment]
Ok and regarding the login what should i do about the password error?

Controller:
```
    public function login()
    {
        if ($_SERVER['REQUEST_METHOD']=='POST') {

            $_POST = filter_input_array(INPUT_POST, FILTER_SANITIZE_STRING);
            $udata = [
                'email' => trim($_POST['email']),
                'password' => trim($_POST['password']),
                'email_err' => '',
                'password_err' => ''
            ];
            $data = [
                'title' => 'Sign into your account',
                'login' => $udata
            ];

            if ( empty($data['login']['email']) ) {
                $data['login']['email_err'] = 'Email is required!';
            } else if (! $this->user->getUserByEmail($data['login']['email']) ) {
                $data['login']['email_err'] = 'Invalid Email / Password';
				$data['login']['password_err'] = 'Invalid Email / Password';
            }
            if ( empty($data['login']['password']) ) {
                $data['login']['password_err'] = 'Password is required!';
            }

            if ( empty($data['login']['email_err']) && empty($data['login']['password_err']) ) {
                $userAuthenticated = $this->user->login($data['login']['email'], $data['login']['password']);
                if ( $userAuthenticated) {
                    $this->createUserSession($userAuthenticated);
                } else {
                    $udata = [
                        'email' => trim($_POST['email']),
                        'password' => '',
                        'email_err' => 'Invalid Email / Password',
                        'password_err' => 'Invalid Email / Password'
                    ];
                    $data = [
                        'title' => 'Sign into your account',
                        'login' => $udata
                    ];
                    $this->view('admin/login', $data);
                }
            } else {
                $this->view('admin/login', $data);
            }
        } else {
            $udata = [
                'email' => '',
                'password' => '',
                'email_err' => '',
                'password_err' => ''
            ];
            $data = [
                'title' => 'Sign into your account',
                'login' => $udata
            ];
            $this->view('admin/login', $data);
        }
    }
```

Model:
```
    public function getUserByEmail($user_id)
    {
        $bind = [':email' => $user_id];
        $results = $this->db->select('chewi_users','email = :email', $bind);
        return $results;
    }

    
    public function login($email,$password)
    {
        $bind = [':email' => $email];
        $results = $this->db->select('chewi_users','email = :email', $bind);
        $hashed_password = $results['password'];
        if ( password_verify($password,$hashed_password) ) {
            return $results;
        } else {
            return false;
        }
    }
```

View:
```
                        <form action="<?php echo FULL_ROOT; ?>/admin/login" method="post" class="f-14">
                            <div class="form-group">
                                <label>E-mail Address</label>
                                <input class="form-control <?php echo (!empty($data['login']['email_err'])) ? 'is-invalid' : '';?>" autofocus="" name="email" placeholder="" type="email" value="<?php echo $data['login']['email']; ?>">
                                <span class="invalid-feedback"><?php echo $data['login']['email_err']; ?></span>
                            </div>
                            <div class="form-group">
                                <label>Password</label>
                                <a href="#" class="float-right">Forgot Password?</a>
                                <input name="password" id="password-field" class="form-control <?php echo (!empty($data['login']['password_err'])) ? 'is-invalid' : '';?>" placeholder="" value="<?php echo $data['login']['password']; ?>" type="password">
                                <span class="invalid-feedback"><?php echo $data['login']['password_err']; ?></span>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary btn-block login-button" type="submit" role="button">Sign In</button>
                            </div>
                            <div class="login-register text-left"><span>Don't have an account?&nbsp;<a class="" href="#">Sign Up</a></span></div>
                        </form>
```

**Comment by sonicsleuth** [comment]
RE: "unlimited categories and subcategories tree system" - you can think of the $data array you pass to the View as the "payload".  It's like a school bus with seats (indexes) and each can have a different type of data in the seat, like (string, string, array, bool, string, etc...)  The "payload" term is common when using JSON objects to deliver data to a Single Page App (SPA).  Just remember the "bus" concept, fill up the seats then do a roll call for your data by seat location. Hope that helped.

**Comment by sonicsleuth** [comment]
I'm not for hire at this time for the pagination, but here are a few items to consider then making yours.

- Always query the data identically between sets. 
- Understand SQL LIMIT length, offset (this is your set)
- Check each set to see if the number of records is less than expected, if true, you hit the end of records.
- Remember where you left off, which set.
- Test if someone shifts the set in the url so the query won't break.
- Are you using Prev/Next or some numbered page links.

**Comment by sonicsleuth** [comment]
I would make an array in the Controller then add it to the $data payload for the View.

CONTROLLER
```
$errors = [ 
   'err_type' = 'error',  // style options: 'error', 'notice', 'warning'
   'err_messages = array() // this array contains 1+ error notices, good for form errors b/c all errors are stated at once.
]
```

then in the VIEW someplace...

```
if( $data['errors']['err_type'] == 'error' ) {
   foreach $data['errors']['err_messages'] {
      // ... echo errors and style them
   }
}
```

**Comment by jackttcoms** [comment]
Oh, i meant i have already finished the categories tree using your logic but thanks and regrading the password issue how should i fix that?  

And i'm gonna use prev/next buttons with numbers but maybe you can let me know when ur ready for hire and then for the time being i can just do a lazy loading pagination.

Also am i doing something wrong with the search? Right now im just doing the basics where im doing the url where you go domain.com/search/????? so here is my controller:

```
    public function search($search)
    {
                $getCategories = $this->blog->getCategories();
        $getSettings = $this->blog->getAll();
        $searchquery = $this->blog->search($search);
                $data = [
            "settings" => $getSettings,
            "searchresults" => $searchquery,
            "getCategories" => $getCategories
        ];
        $this->view('search', $data);
    }
```

Here is my model:
```
    public function search($search)
    {
        $bind = array(
            ":search" => "%$search"
         );
        $results = $this->db->select("chewi_posts", "title LIKE :search", $bind);
        return $results;
    }
```

Here is my view:
```
                <?php var_dump($data['searchresults']); if( $data['searchresults'] == FALSE ) { ?>

          <div class="col-12"><div class="alert alert-primary shadow-1" role="alert">
                <b><i class="fas fa-info-circle"></i> Blog Empty!</b>
           </div></div>

<?php } else {   foreach($data['searchresults'] as $post) : ?>

          <div class="col-lg-4 col-md-4 col-sm-6 mb-3">
                        <div class="card h-100 shadow-1">
                            <a href="<?php echo FULL_ROOT;?>/post/<?php echo $post['id']; ?>/">
                                <img class="card-img-top" src="<?php echo $post['image']; ?>" alt="<?php echo $post['title']; ?>">
                            </a>
                            <div class="card-body text-center">
                                <a href="<?php echo FULL_ROOT;?>/post/<?php echo $post['id']; ?>/"><h2 class="card-title font-weight-bold f-18"><?php echo $post['title']; ?></h2></a>
                            </div>
                        </div>
                    </div>

<?php endforeach;  } ?>
```

And the return currently from the var_dump is bool(false) so am i being really stupid? I feel like i'm missing something really big.

Thanks

**Comment by jackttcoms** [comment]
its ok i fixed the login now! To fix i did this:
```
    public function login($email,$password)
    {
        $bind = [':email' => $email];
        $results = $this->db->select('msi_users','email = :email', $bind);
        $hashed_password = $results[0]['password'];
        if ( password_verify($password,$hashed_password) ) {
			$this->lastlogin($email);
            return $results;
        } else {
            return false;
        }
    }
```
```
    public function createUserSession($user)
    {
        $_SESSION['uid'] = $user[0]['id'];
        $_SESSION['uemail'] = $user[0]['email'];
        $_SESSION['uname'] = $user[0]['username'];
        $_SESSION['ufname'] = $user[0]['name'];
        $_SESSION['uprofile'] = $user[0]['profile'];
        $_SESSION['ujdate'] = $user[0]['joined'];
        if ($user[0]['activate_author']) {
            $_SESSION['uauthor'] = true;
        }
        $_SESSION['utoken'] = hash('sha256', uniqid());
        flash('login_success','You have logged in successfully!','alert alert-success mb-0');
        redirect('');
    }
```

**Comment by sonicsleuth** [comment]
Good to hear that. Persistence pays off.
